import type { HeroSlide } from "./types";

export const BOOK_HERO_SLIDE_VARIANTS = {
  enter: (direction: number) => ({
    x: direction > 0 ? "100%" : "-100%",
    opacity: 0,
  }),
  center: {
    x: 0,
    opacity: 1,
  },
  exit: (direction: number) => ({
    x: direction > 0 ? "-100%" : "100%",
    opacity: 0,
  }),
};

export const BOOK_HERO_BLUR_DATA_URL =
  "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAICAgIChsICQkJChAODwoQFwwTGB8WFBcUFRYaFxwpHhcYGRgaGBgSHBwcHhcYGhj/2wBDAQcHBwoIChMICQsMCggKGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBj/wAARCABkAGQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWm5ybnJ2eoqOkpaanqKmqsrO0tba2uLm6wsPExcbHyMnK0tPU1dbW2Nna4uPk5ebn6Onq8vP09fb2+Pn6/8QAHwEAAwEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlbaWmJmaoqOkpaanqKmqsrO0tba2uLm6wsPExcbHyMnK0tPU1dbW2Nna4uPk5ebn6Onq8vP09fb2+Pn6/9oAMBAAIRAxEAPwD3+iiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigD//Z";

export const bookHeroData: Record<string, { slides: HeroSlide[] }> = {
  en: {
    slides: [
      {
        id: "isolele",
        type: "book",
        tag: "WELCOME TO ISOLELE",
        title: "THE CHOSEN ONES",
        subtitle: "AN ENTIRE UNIVERSE BORN FROM THE ROOTS OF KONGO...",
        description:
          "Isolele is a visionary universe born to restore the soul of African storytelling, a mythological empire where superheroes are chosen by destiny, kingdoms never forgotten, and ancestral power is alive in every page, every prophecy, every battle. Every child who reads Isolele will discover superheroes who look like them, speak their language, protect their land, and honor their ancestors. This is for the next generation of kings, queens, warriors, inventors, and storytellers.",
        buttonText: "EXPLORE THE UNIVERSE",
        image:
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Cover%20Book%202%20Isolele-QCEiRH2KJp3oFt4O31Qocqap3nLgiJ.jpg",
        href: "/books/isolele",
        accentColor: "#F6B800",
      },
      {
        id: "zaiire",
        type: "book",
        tag: "ZAIIRE: THE PRINCE OF KONGO",
        title: "ZAIIRE",
        subtitle: "THE NECKLACE OF DESTINY",
        description:
          "Forged in the heart of the Kongo Kingdom, the Necklace of Destiny was never made to be worn. It was made to choose. Passed through centuries of fire, war, and silence, it carries the soul of every king who bled for their people and every queen who held the world together with bare hands. When it finds Zaiire, it does not shine. It awakens.",
        buttonText: "DISCOVER ZAIIRE",
        image: "/images/zaiire-cover-2026.webp",
        href: "/books/zaiire",
        accentColor: "#F6B800",
      },
      {
        id: "makanda",
        type: "book",
        tag: "THE MAKANDA DYNASTY - BOOK I",
        title: "MAKANDA",
        subtitle: "THE RISING KANDAKE",
        description:
          "Deep within Central Africa existed a civilization the world was never meant to know about. Spiritually awakened. Technologically advanced. Protected by the Sacred Flame. When outside forces came for what was theirs, the Makanda did not fall. They disappeared. Their city was never lost. It was waiting for the one born to carry the flame again.",
        buttonText: "DISCOVER MAKANDA",
        image:
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/KIMOYA%20-%20THE%20RISING%20KANDAKE-kpNHOGXUp1l9A5z7uJ2Z4kI3v7e0ek.jpg",
        href: "/books/makanda",
        accentColor: "#C0392B",
      },
      {
        id: "bambula",
        type: "book",
        tag: "BAMBULA: CHILD OF RHYTHM",
        title: "BAMBULA",
        subtitle: "CHAPTER I · THE SACRED DRUM",
        description:
          "Before words, there was rhythm. Bambula was the child who heard everything. When the drums were taken and the land went silent, he kept the rhythm alive inside him. Armed with the sacred drum, he walks between the spirit world and the living. He does not fight to destroy. He protects to remember.",
        buttonText: "DISCOVER BAMBULA",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Bambula%201-UAlmQoZVy1GslUfmVvqc5bdDDdEQdX.jpg",
        href: "/books/bambula",
        accentColor: "#B3541E",
      },
      {
        id: "mokele",
        type: "book",
        tag: "MOKELE: BORN INTO STRUGGLE",
        title: "MOKELE",
        subtitle: "FROM CHILD TO LORD OF KINSHASA",
        description:
          "Mokele is not born a king. He is born into struggle. The streets of Kinshasa teach him before school ever could, where loyalty is fragile, violence is normal, and survival is everything. From child to hustler to lord. He builds power, money, and respect. In Kinshasa, you either get eaten... Or you become the predator.",
        buttonText: "DISCOVER MOKELE",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Mokele.png-7sTyiUJYN8wJbiGll8YdVThtR4F8FT.jpeg",
        href: "/books/mokele",
        accentColor: "#4169E1",
      },
      {
        id: "kufu",
        type: "book",
        tag: "KUFU: THE CROWN GAME",
        title: "KUFU",
        subtitle: "THE OFFICIAL GAME OF THE ISOLELE UNIVERSE",
        description:
          "This is not just a card game. It is a ceremony. Gather your warriors. Build your kingdom. Outplay every opponent at the table. But to claim the crown there is only one way to win. You must raise your voice and speak the name of the king out loud. Then someone places the necklace over your head. Not by your own hand. By another. Because a true king is not crowned alone. KUFU is where African royalty becomes something you feel in your hands, hear in your voice, and carry around your neck. Every game is a coronation. Every winner is a king.",
        buttonText: "EXPLORE THE GAME",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_20260321_113436-ktAJOL2e0SS0pkTY6aPnn7aBKxr3pq.jpg",
        href: "/books/kufu",
        accentColor: "#F8B90D",
      },
      {
        id:"zattar",
        type: "book",
        tag: "ZATTAR: THE PRINCE OF THE UNIVERSE",
        title: "ZATTAR",
        subtitle: "THE CONQUEROR OF THRONES",
        description:
          "When Destiny Refused Him One Kingdom, He Decided to Take Them All. Prince Zattar was born to inherit the throne of Bapindi. But when the Ancestors chose another, something inside him did not break. It ignited. He studied the First and Second Wars of Vegas, legends of devastation that shook the world before he was even born. Where others saw warning, Zattar saw a map. He started the Third War of Vegas. Not out of madness. Not out of pain. But because he looked at the entire universe and reached one conclusion: It belongs to someone. And that someone is Zattar. He was not chosen. So he chose the universe instead.",
        buttonText: "DISCOVER ZATTAR",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/e9c64c65-3717-4fe3-a391-885767df3303-LbjnMwCViF43pwErKmoFv7iGxQdCeQ.jpeg",
        href: "/books/zattar",
        accentColor: "#2E8B57",
      },
      {
        id: "amara",
        type: "book",
        tag: "AMARA: QUEEN OF THE SEAS",
        title: "AMARA",
        subtitle: "CHAPTER I · QUEEN OF THE PIRATES OF AMAZON",
        description:
          "Every pirate fears the ocean. Amara owns it. She is the Queen of the Seas. The most feared captain on every water in the world. No ship has outrun her. No king has outsmarted her. No army has stopped her fleet. But Amara does not sail alone. Beside her stand four women bound by blood, loyalty and destiny. Five queens of the sea who together carry a power that will shake every throne on the continent. From their union the Agojie dynasty is born. And from that dynasty rise the five women kings who will change the course of African history forever.",
        buttonText: "DISCOVER AMARA",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1173-wrVJYiZhuW6ZvCM0Xronsu544ccrqV.jpeg",
        href: "/#hero",
        accentColor: "#1E90B3",
      },
      {
        id: "zaiko",
        type: "book",
        tag: "ZAIKO: LAST KING OF THE STREETS OF KIVUS",
        title: "ZAIKO",
        subtitle: "THE LEGEND OF ZAIKO",
        description:
          "Born in North Kivu. Forged in Kinshasa. Zaiko was never meant to survive. But survival was never enough. In a world ruled by power, money, and fear, he rises from nothing. Not as a hero. But as a force. With his brother, he builds the most feared empire the Kivus have ever known. No crown was given. No destiny was written. Everything was taken. Every empire built from the ashes of those who came before. This is the legend of how one man defied fate itself and carved his name into African history with iron and will.",
        buttonText: "DISCOVER ZAIKO",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1175-njlosetUOsqZszKylrOXsIRLw0l3s7.jpeg",
        href: "/books/zaiko",
        accentColor: "#2E8B57",
      }
    ]
  },
  pt: {
    slides: [
      {
        id: "isolele",
        type: "book",
        tag: "BEM-VINDO A ISOLELE",
        title: "O ESCOLHIDO",
        subtitle: "O PRIMEIRO UNIVERSO DE SUPER-HERÓIS AFRICANOS NEGROS",
        description:
          "Isolele é um universo visionário nascido para restaurar a alma da narrativa africana, um império mitológico onde os super-heróis são escolhidos pelo destino, reinos nunca esquecidos, e o poder ancestral vive em cada página, cada profecia, cada batalha. Toda criança que ler Isolele vai descobrir super-heróis que se parecem com ela, falam a sua língua, protegem a sua terra e honram os seus ancestrais. Isto é para a próxima geração de reis, rainhas, guerreiros, inventores e contadores de histórias. A ISOLELE é o primeiro universo de super-heróis africanos negros enraizado na herança autêntica do Kongo, criado na RDC e construído para o mundo.",
        buttonText: "EXPLORAR O UNIVERSO",
        image:
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Cover%20Book%202%20Isolele-QCEiRH2KJp3oFt4O31Qocqap3nLgiJ.jpg",
        href: "/books/isolele",
        accentColor: "#F6B800",
      },
      {
        id: "zaiire",
        type: "book",
        tag: "ZAIIRE: PRÍNCIPE DO KONGO",
        title: "ZAIIRE",
        subtitle: "O COLAR DO DESTINO",
        description:
          "Zaiire não nasce herói. Nasce escolhido. Filho de Shango, o senhor divino do trovão, e da Princesa Kimoya, uma rainha guerreira da linhagem real do Kongo, Zaiire carrega dois mundos dentro de si. O mundo mortal de reis, guerras e sacrifício. E o mundo divino do poder ancestral, do destino cósmico e de forças mais antigas que qualquer reino.",
        buttonText: "DESCOBRIR ZAIIRE",
        image: "/images/zaiire-cover-2026.webp",
        href: "/books/zaiire",
        accentColor: "#F6B800",
      },
      {
        id: "makanda",
        type: "book",
        tag: "A DINASTIA MAKANDA - LIVRO I",
        title: "MAKANDA",
        subtitle: "A DINASTIA ESCONDIDA",
        description:
          "No coração da África Central existia uma civilização que o mundo nunca deveria conhecer. Espiritualmente desperta. Tecnologicamente avançada. Protegida pela Chama Sagrada. Quando forças externas vieram atrás do que era deles, os Makanda não caíram. Desapareceram. A sua cidade nunca se perdeu. Estava à espera daquele que nasceu para carregar a chama de novo. A Dinastia Makanda é uma série de comics africanos negros nascida da civilização Kongo, um império escondido a erguer-se do coração da RDC.",
        buttonText: "DESCOBRIR MAKANDA",
        image:
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/KIMOYA%20-%20THE%20RISING%20KANDAKE-kpNHOGXUp1l9A5z7uJ2Z4kI3v7e0ek.jpg",
        href: "/books/makanda",
        accentColor: "#C0392B",
      },
      {
        id: "bambula",
        type: "book",
        tag: "BAMBULA: FILHO DO RITMO",
        title: "BAMBULA",
        subtitle: "O TAMBOR SAGRADO",
        description:
          "Antes das palavras, havia o ritmo. Bambula era a criança que ouvia tudo. Quando os tambores foram tirados e a terra ficou em silêncio, ele manteve o ritmo vivo dentro de si. Armado com o tambor sagrado, caminha entre o mundo espiritual e os vivos. Não luta para destruir. Protege para lembrar. Bambula é um super-herói africano negro enraizado na tradição espiritual do Kongo, onde o tambor sagrado liga os vivos aos ancestrais.",
        buttonText: "DESCOBRIR BAMBULA",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Bambula%201-UAlmQoZVy1GslUfmVvqc5bdDDdEQdX.jpg",
        href: "/books/bambula",
        accentColor: "#B3541E",
      },
      {
        id: "mokele",
        type: "book",
        tag: "MOKELE: DE CRIANÇA A SENHOR",
        title: "MOKELE",
        subtitle: "DAS RUAS DE KINSHASA",
        description:
          "Mokele não nasce rei. Nasce na luta. As ruas de Kinshasa ensinam-no antes de qualquer escola, onde a lealdade é frágil, a violência é normal e a sobrevivência é tudo. De criança a vigarista a senhor. Ele constrói poder, dinheiro e respeito. Em Kinshasa, ou és devorado... ou tornas-te o predador. Mokele é uma personagem de comics africana negra nascida nas ruas de Kinshasa, RDC, onde a sobrevivência constrói impérios.",
        buttonText: "DESCOBRIR MOKELE",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Mokele.png-7sTyiUJYN8wJbiGll8YdVThtR4F8FT.jpeg",
        href: "/books/mokele",
        accentColor: "#4169E1",
      },
      {
        id: "kufu",
        type: "book",
        tag: "KUFU: JOGO DE CARTAS PAN-AFRICANO",
        title: "KUFU",
        subtitle: "103 CARTAS. UMA COROA.",
        description:
          "Isto não é apenas um jogo de cartas. É uma cerimónia. Reúna os seus guerreiros. Construa o seu reino. Supere todos os adversários à mesa. Mas para reivindicar a coroa há apenas uma forma de vencer. Tens de erguer a voz e dizer o nome do rei em voz alta. Depois alguém coloca o colar sobre a tua cabeça. Não pela tua própria mão. Por outra pessoa. Porque um verdadeiro rei não se coroa sozinho. KUFU é onde a realeza africana se torna algo que sentes nas mãos, ouves na tua voz e carregas ao pescoço. Cada jogo é uma coroação. Cada vencedor é um rei. Kufu é o primeiro jogo de cartas pan-africano com reis, rainhas e guerreiros africanos da civilização Kongo. 103 cartas. Uma coroa. A ser lançado em 30 de junho de 2026.",
        buttonText: "DESCOBRIR KUFU",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_20260321_113436-ktAJOL2e0SS0pkTY6aPnn7aBKxr3pq.jpg",
        href: "/books/kufu",
        accentColor: "#F8B90D",
      },
      {
        id: "zattar",
        type: "book",
        tag: "ZATTAR: O ÚLTIMO PRÍNCIPE",
        title: "ZATTAR",
        subtitle: "O ÚLTIMO PRÍNCIPE DO KONGO",
        description:
          "Quando o Destino Lhe Recusou Um Reino, Ele Decidiu Tomá-los Todos. O Príncipe Zattar nasceu para herdar o trono de Bapindi. Mas quando os Ancestrais escolheram outro, algo dentro dele não se quebrou. Incendiou-se. Estudou a Primeira e a Segunda Guerra de Vegas, lendas de devastação que abalaram o mundo antes mesmo de ele nascer. Onde outros viam um aviso, Zattar viu um mapa. Iniciou a Terceira Guerra de Vegas. Não por loucura. Não por dor. Mas porque olhou para o universo inteiro e chegou a uma conclusão: Pertence a alguém. E esse alguém é Zattar. Ele não foi escolhido. Por isso escolheu o universo. Zattar é o vilão africano negro mais perigoso dos comics, um Príncipe de Bapindi que recusou o destino e declarou guerra ao universo inteiro.",
        buttonText: "DESCOBRIR ZATTAR",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/e9c64c65-3717-4fe3-a391-885767df3303-LbjnMwCViF43pwErKmoFv7iGxQdCeQ.jpeg",
        href: "/books/zattar",
        accentColor: "#2E8B57",
      },
      {
        id: "amara",
        type: "book",
        tag: "AMARA: A PRINCESA REBELDE",
        title: "AMARA",
        subtitle: "A PRINCESA REBELDE DO KONGO",
        description:
          "Amara é uma princesa rebelde do Kongo. A filha feroz de um rei poderoso, ela desafia a tradição e luta pela justiça num mundo que tenta silenciá-la. Quando o seu reino é ameaçado por forças externas, Amara pega em armas para proteger o seu povo e reclamar o seu lugar de direito no trono. Amara é uma personagem de comics africana negra nascida da linhagem real da civilização Kongo, onde as princesas não são apenas figuras de beleza, mas guerreiras destinadas a liderar o seu povo até à vitória.",
        buttonText: "DESCOBRIR AMARA",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1173-wrVJYiZhuW6ZvCM0Xronsu544ccrqV.jpeg",
        href: "/#hero",
        accentColor: "#1E90B3",
      },
      {
        id: "zaiko",
        type: "book",
        tag: "ZAIKO: O ÚLTIMO REI DAS RUAS DE KIVU",
        title: "ZAIKO",
        subtitle: "A LENDA DE ZAIKO",
        description:
          "Nascido em Kivu do Norte. Forjado em Kinshasa. Zaiko nunca deveria sobreviver. Mas sobreviver nunca foi suficiente. Num mundo governado pelo poder, dinheiro e medo, ele ergue-se do nada. Não como herói. Mas como uma força. Com o seu irmão, constrói o império mais temido que os Kivus já conheceram. Nenhuma coroa foi dada. Nenhum destino foi escrito. Tudo foi tomado. Cada império construído sobre as cinzas dos que vieram antes. Esta é a lenda de como um homem desafiou o próprio destino e gravou o seu nome na história africana com ferro e vontade. Zaiko é um herói de comics africano negro nascido em Kivu do Norte, RDC, onde a guerra forjou o rei mais temido que as ruas já conheceram.",
        buttonText: "DESCOBRIR ZAIKO",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1175-njlosetUOsqZszKylrOXsIRLw0l3s7.jpeg",
        href: "/books/zaiko",
        accentColor: "#2E8B57",
      }
    ]
  },

  fr:{
    slides: [
      {
        id: "isolele",
        type: "book",
        tag: "BIENVENUE À ISOLELE",
        title: "LES ÉLUS",
        subtitle: "UN UNIVERS ENTIER NÉ DES RACINES DU KONGO...",
        description:
          "Isolele est un univers visionnaire né pour restaurer l'âme de la narration africaine, un empire mythologique où les super-héros sont choisis par le destin, où les royaumes ne sont jamais oubliés, et où la puissance ancestrale est vivante à chaque page, chaque prophétie, chaque bataille. Chaque enfant qui lira Isolele découvrira des super-héros qui lui ressemblent, parlent sa langue, protègent sa terre et honorent ses ancêtres. Ceci est pour la prochaine génération de rois, reines, guerriers, inventeurs et conteurs.",
        buttonText: "EXPLORER L'UNIVERS",
        image:
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Cover%20Book%202%20Isolele-QCEiRH2KJp3oFt4O31Qocqap3nLgiJ.jpg",
        href: "/books/isolele",
        accentColor: "#F6B800",
      },
      {
        id: "zaiire",
        type: "book",
        tag: "ZAIIRE : LE PRINCE DU KONGO",
        title: "ZAIIRE",
        subtitle: "LE COLLIER DU DESTIN",
        description:
          "Forgé au cœur du Royaume du Kongo, le Collier du Destin n'a jamais été fait pour être porté. Il a été fait pour choisir. Transmis à travers des siècles de feu, de guerre et de silence, il porte l'âme de chaque roi qui a saigné pour son peuple et de chaque reine qui a tenu le monde ensemble à mains nues. Quand il trouve Zaiire, il ne brille pas. Il s'éveille.",
        buttonText: "DÉCOUVRIR ZAIIRE",
        image: "/images/zaiire-cover-2026.webp",
        href: "/books/zaiire",
        accentColor: "#F6B800",
      },
      {
        id: "makanda",
        type: "book",
        tag: "LA DYNASTIE MAKANDA - LIVRE I",
        title: "MAKANDA",
        subtitle: "LA KANDAKE ASCENDANTE",
        description:
          "Au cœur de l'Afrique centrale existait une civilisation que le monde n'était jamais censé connaître. Éveillée spirituellement. Technologiquement avancée. Protégée par la Flamme Sacrée. Quand des forces extérieures sont venues prendre ce qui leur appartenait, les Makanda ne sont pas tombés. Ils ont disparu. Leur ville n'a jamais été perdue. Elle attendait celui qui était né pour porter à nouveau la flamme.",
        buttonText: "DÉCOUVRIR MAKANDA",
        image:
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/KIMOYA%20-%20THE%20RISING%20KANDAKE-kpNHOGXUp1l9A5z7uJ2Z4kI3v7e0ek.jpg",
        href: "/books/makanda",
        accentColor: "#C0392B",
      },
      {
        id: "bambula",
        type: "book",
        tag: "BAMBULA : ENFANT DU RYTHME",
        title: "BAMBULA",
        subtitle: "CHAPITRE I · LE TAMBOUR SACRÉ",
        description:
          "Avant les mots, il y avait le rythme. Bambula était l'enfant qui entendait tout. Quand les tambours furent emportés et que la terre devint silencieuse, il garda le rythme vivant à l'intérieur de lui. Armé du tambour sacré, il marche entre le monde des esprits et celui des vivants. Il ne combat pas pour détruire. Il protège pour se souvenir.",
        buttonText: "DÉCOUVRIR BAMBULA",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Bambula%201-UAlmQoZVy1GslUfmVvqc5bdDDdEQdX.jpg",
        href: "/books/bambula",
        accentColor: "#B3541E",
      },
      {
        id: "mokele",
        type: "book",
        tag: "MOKELE : NÉ DANS LA LUTTE",
        title: "MOKELE",
        subtitle: "DE L'ENFANT AU SEIGNEUR DE KINSHASA",
        description:
          "Mokele n'est pas né roi. Il est né dans la lutte. Les rues de Kinshasa lui apprennent ce que l'école n'aurait jamais pu lui apprendre, là où la loyauté est fragile, la violence normale et la survie primordiale. De l'enfant au débrouillard puis au seigneur. Il construit le pouvoir, l'argent et le respect. À Kinshasa, soit on se fait dévorer… Soit on devient le prédateur.",
        buttonText: "DÉCOUVRIR MOKELE",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Mokele.png-7sTyiUJYN8wJbiGll8YdVThtR4F8FT.jpeg",
        href: "/books/mokele",
        accentColor: "#4169E1",
      },
      {
        id: "kufu",
        type: "book",
        tag: "KUFU : LE JEU DE LA COURONNE",
        title: "KUFU",
        subtitle: "LE JEU OFFICIEL DE L'UNIVERS ISOLELE",
        description:
          "Ce n'est pas qu'un simple jeu de cartes. C'est une cérémonie. Rassemblez vos guerriers. Bâtissez votre royaume. Surpassez tous vos adversaires à la table. Mais pour revendiquer la couronne, il n'y a qu'une seule façon de gagner. Vous devez élever la voix et prononcer le nom du roi à haute voix. Ensuite, quelqu'un vous passe le collier autour du cou. Pas de votre propre main. Par une autre. Parce qu'un vrai roi n'est pas couronné seul. KUFU est l'endroit où la royauté africaine devient quelque chose que l'on sent dans ses mains, que l'on entend dans sa voix et que l'on porte autour de son cou. Chaque partie est un couronnement. Chaque gagnant est un roi.",
        buttonText: "EXPLORER LE JEU",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_20260321_113436-ktAJOL2e0SS0pkTY6aPnn7aBKxr3pq.jpg",
        href: "/books/kufu",
        accentColor: "#F8B90D",
      },
      {
        id:"zattar",
        type: "book",
        tag: "ZATTAR : LE PRINCE DE L'UNIVERS",
        title: "ZATTAR",
        subtitle: "LE CONQUÉRANT DES TRÔNES",
        description:
          "Quand le Destin lui a refusé un royaume, il a décidé de les prendre tous. Le prince Zattar est né pour hériter du trône de Bapindi. Mais quand les Ancêtres en ont choisi un autre, quelque chose en lui ne s'est pas brisé. Cela s'est enflammé. Il a étudié la Première et la Deuxième Guerre de Vegas, des légendes de dévastation qui ont secoué le monde avant même sa naissance. Là où d'autres voyaient un avertissement, Zattar a vu une carte. Il a déclenché la Troisième Guerre de Vegas. Non par folie. Non par douleur. Mais parce qu'il a regardé l'univers entier et a tiré une conclusion : il appartient à quelqu'un. Et ce quelqu'un, c'est Zattar. Il n'a pas été choisi. Alors il a choisi l'univers à la place.",
        buttonText: "DÉCOUVRIR ZATTAR",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/e9c64c65-3717-4fe3-a391-885767df3303-LbjnMwCViF43pwErKmoFv7iGxQdCeQ.jpeg",
        href: "/books/zattar",
        accentColor: "#2E8B57",
      },
      {
        id: "amara",
        type: "book",
        tag: "AMARA : REINE DES MERS",
        title: "AMARA",
        subtitle: "CHAPITRE I · REINE DES PIRATES D'AMAZONIE",
        description:
          "Tout pirate craint l'océan. Amara le possède. Elle est la Reine des Mers. Le capitaine le plus craint sur toutes les eaux du monde. Aucun navire ne lui a échappé. Aucun roi ne l'a surpassée en ruse. Aucune armée n'a arrêté sa flotte. Mais Amara ne navigue pas seule. À ses côtés se tiennent quatre femmes liées par le sang, la loyauté et le destin. Cinq reines des mers qui portent ensemble un pouvoir qui ébranlera tous les trônes du continent. De leur union naît la dynastie Agojie. Et de cette dynastie s'élèvent les cinq femmes rois qui changeront à jamais le cours de l'histoire africaine.",
        buttonText: "DÉCOUVRIR AMARA",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1173-wrVJYiZhuW6ZvCM0Xronsu544ccrqV.jpeg",
        href: "/#hero",
        accentColor: "#1E90B3",
      },
      {
        id: "zaiko",
        type: "book",
        tag: "ZAIKO : DERNIER ROI DES RUES DES KIVUS",
        title: "ZAIKO",
        subtitle: "LA LÉGENDE DE ZAIKO",
        description:
          "Né au Nord-Kivu. Forgé à Kinshasa. Zaiko n'était jamais censé survivre. Mais survivre n'a jamais suffi. Dans un monde régi par le pouvoir, l'argent et la peur, il s'élève à partir de rien. Non pas en tant que héros. Mais en tant que force. Avec son frère, il bâtit l'empire le plus redouté que les Kivus aient jamais connu. Aucune couronne n'a été donnée. Aucun destin n'a été écrit. Tout a été pris. Chaque empire construit sur les cendres de ceux qui l'ont précédé. Voici la légende de comment un homme a défié le destin lui-même et gravé son nom dans l'histoire africaine avec du fer et de la volonté.",
        buttonText: "DÉCOUVRIR ZAIKO",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1175-njlosetUOsqZszKylrOXsIRLw0l3s7.jpeg",
        href: "/books/zaiko",
        accentColor: "#2E8B57",
      }
    ]
  },

  
    ln: {
      slides: [
        {
          id: "isolele",
          type: "book",
          tag: "BOYEI BOLAMU NA ISOLELE",
          title: "MOPONAMI",
          subtitle: "MOKILI YA LIBOSO YA BA SUPER-HÉROS YA AFRIKA",
          description: "Isolele ezali bokonzi ya kala epai ba super-héros baponami na likambo ya lola. Mwana nyonso oyo akotanga Isolele akomona ba super-héros oyo bafani na ye mpe bakumisaka bankoko na ye. Esalami na RDC mpo na mokili mobimba.",
          buttonText: "KOTA NA MOKILI OYO",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Cover%20Book%202%20Isolele-QCEiRH2KJp3oFt4O31Qocqap3nLgiJ.jpg",
          href: "/books/isolele",
          accentColor: "#F6B800",
        },
        {
          id: "zaiire",
          type: "book",
          tag: "ZAIIRE : MWANA-KONZI YA KONGO",
          title: "ZAIIRE",
          subtitle: "ELOKO YA MOTEMA YA LIKAMBO YA LOLA",
          description: "Zaiïre abotami moponami. Mwana ya Shango mpe Princess Kimoya, amemi mikili mibale na kati na ye: mokili ya bato mpe nguya ya bankoko.",
          buttonText: "YREBA ZAIIRE",
          image: "/images/zaiire-cover-2026.webp",
          href: "/books/zaiire",
          accentColor: "#F6B800",
        },
        {
          id: "makanda",
          type: "book",
          tag: "DYNASTIE MAKANDA",
          title: "MAKANDA",
          subtitle: "BOKONZI EBOMBAMA",
          description: "Na kati ya Afrika, bokonzi moko ya mayele makasi ebombamaki mpo na kobatela munda ya bule. Basengelaki kozela moponami mpo na kopelisa munda yango lisusu.",
          buttonText: "YREBA MAKANDA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/KIMOYA%20-%20THE%20RISING%20KANDAKE-kpNHOGXUp1l9A5z7uJ2Z4kI3v7e0ek.jpg",
          href: "/books/makanda",
          accentColor: "#C0392B",
        },
        {
          id: "bambula",
          type: "book",
          tag: "BAMBULA : MWANA YA MIZIKI",
          title: "BAMBULA",
          subtitle: "LOKOLE YA BULE",
          description: "Na lokole na ye ya bule, Bambula atambolaka kati na mokili ya milimo mpe ya bato. Abundaka mpo na kobebisa te, kasi mpo na kobatela mimeseno ya bankoko.",
          buttonText: "YREBA BAMBULA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Bambula%201-UAlmQoZVy1GslUfmVvqc5bdDDdEQdX.jpg",
          href: "/books/bambula",
          accentColor: "#B3541E",
        },
        {
          id: "mokele",
          type: "book",
          tag: "MOKELE : MOKONZI YA BALABALA",
          title: "MOKELE",
          subtitle: "BALABALA YA KINSHASA",
          description: "Balabala ya Kinshasa eteyi ye bomoi yambo ya kelasi. Kobanda mwana ya moke tii na kokoma nkolo mokili, amonisi ete na Kinshasa, soki ozali mayele te, bakoliya yo.",
          buttonText: "YREBA MOKELE",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Mokele.png-7sTyiUJYN8wJbiGll8YdVThtR4F8FT.jpeg",
          href: "/books/mokele",
          accentColor: "#4169E1",
        },
        {
          id: "kufu",
          type: "book",
          tag: "KUFU : MASANO YA CARTES",
          title: "KUFU",
          subtitle: "103 CARTES. MOTOLE MOKO.",
          description: "Oyo ezali kaka lisano te, ezali feti ya bokonzi. Tonga bokonzi na yo mpe longola nkombo ya mokonzi na mongongo makasi mpo na kozwa motole.",
          buttonText: "YREBA KUFU",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_20260321_113436-ktAJOL2e0SS0pkTY6aPnn7aBKxr3pq.jpg",
          href: "/books/kufu",
          accentColor: "#F8B90D",
        },
        {
          id: "zattar",
          type: "book",
          tag: "ZATTAR : PRINCE YA MBANDA",
          title: "ZATTAR",
          subtitle: "MWANA-KONZI YA NSUKA YA KONGO",
          description: "Lokola bapesaki ye bokonzi te, azwi mokano ya kozwa mokili mobimba na makasi. Zattar azali monguna ya mabe koleka na lisolo ya Isolele.",
          buttonText: "YREBA ZATTAR",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/e9c64c65-3717-4fe3-a391-885767df3303-LbjnMwCViF43pwErKmoFv7iGxQdCeQ.jpeg",
          href: "/books/zattar",
          accentColor: "#2E8B57",
        },
        {
          id: "amara",
          type: "book",
          tag: "AMARA : MWANA-KONZI YA BITUMBA",
          title: "AMARA",
          subtitle: "PRINCESSE REBELLE",
          description: "Mwana ya mokonzi oyo aboyi mimeseno ya pamba. Amara azali mwanamoke ya bitumba oyo atelemeli mbeba nyonso mpo na kobatela bato na ye.",
          buttonText: "YREBA AMARA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1173-wrVJYiZhuW6ZvCM0Xronsu544ccrqV.jpeg",
          href: "/#hero",
          accentColor: "#1E90B3",
        },
        {
          id: "zaiko",
          type: "book",
          tag: "ZAIKO : MOKONZI YA KIVU",
          title: "ZAIKO",
          subtitle: "LISOLO YA ZAIKO",
          description: "Abotami na Nord-Kivu, akoli na Kinshasa. Zaiko azwi nkombo na ye na bitumba mpe na makila. Azali moko ya bato ya mabe oyo balekisa ndelo na nguya.",
          buttonText: "YREBA ZAIKO",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1175-njlosetUOsqZszKylrOXsIRLw0l3s7.jpeg",
          href: "/books/zaiko",
          accentColor: "#2E8B57",
        }
      ]
    },

    sw: {
      slides: [
        {
          id: "isolele",
          type: "book",
          tag: "KARIBU ISOLELE",
          title: "MTEULE",
          subtitle: "ULIMWENGU WA KWANZA WA MASHUJAA WEUSI",
          description: "Isolele ni milki ya kihadithi ambapo mashujaa huchaguliwa na hatima kurejesha roho ya hadithi za Kiafrika. Kila mtoto atagundua mashujaa wanaofanana naye.",
          buttonText: "GUNDUA ULIMWENGU",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Cover%20Book%202%20Isolele-QCEiRH2KJp3oFt4O31Qocqap3nLgiJ.jpg",
          href: "/books/isolele",
          accentColor: "#F6B800",
        },
        {
          id: "zaiire",
          type: "book",
          tag: "ZAIIRE: MWANAMFALME WA KONGO",
          title: "ZAIIRE",
          subtitle: "MKUFU WA HATIMA",
          description: "Zaiire hakuzaliwa shujaa, alizaliwa mteule. Mwana wa Shango na Princess Kimoya, amebeba ulimwengu wa binadamu na nguvu za mababu.",
          buttonText: "MFAHAMU ZAIIRE",
          image: "/images/zaiire-cover-2026.webp",
          href: "/books/zaiire",
          accentColor: "#F6B800",
        },
        {
          id: "makanda",
          type: "book",
          tag: "ENZI YA MAKANDA",
          title: "MAKANDA",
          subtitle: "ENZI ILIYOFICHWA",
          description: "Ustaarabu wa siri katikati ya Afrika. Walipofatwa na maadui, Makanda walitoweka kulinda Moto Mtakatifu wakingoja mbeba moto mpya.",
          buttonText: "MFAHAMU MAKANDA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/KIMOYA%20-%20THE%20RISING%20KANDAKE-kpNHOGXUp1l9A5z7uJ2Z4kI3v7e0ek.jpg",
          href: "/books/makanda",
          accentColor: "#C0392B",
        },
        {
          id: "bambula",
          type: "book",
          tag: "BAMBULA: MTOTO WA MDUNDO",
          title: "BAMBULA",
          subtitle: "NGOMA TAKATIFU",
          description: "Akiwa na ngoma takatifu, Bambula anatembea kati ya ulimwengu wa roho na walio hai ili kulinda kumbukumbu za mababu.",
          buttonText: "MFAHAMU BAMBULA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Bambula%201-UAlmQoZVy1GslUfmVvqc5bdDDdEQdX.jpg",
          href: "/books/bambula",
          accentColor: "#B3541E",
        },
        {
          id: "mokele",
          type: "book",
          tag: "MOKELE: KUTOKA MITAANI",
          title: "MOKELE",
          subtitle: "MITAA YA KINSHASA",
          description: "Mokele hakuzaliwa mfalme. Mitaa ya Kinshasa ilimfundisha kuishi. Alijenga himaya yake kwa nguvu na heshima katika mji usiokuwa na huruma.",
          buttonText: "MFAHAMU MOKELE",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Mokele.png-7sTyiUJYN8wJbiGll8YdVThtR4F8FT.jpeg",
          href: "/books/mokele",
          accentColor: "#4169E1",
        },
        {
          id: "kufu",
          type: "book",
          tag: "KUFU: MCHEZO WA KADI",
          title: "KUFU",
          subtitle: "KADI 103. TAJI MOJA.",
          description: "Mkusanyiko wa wapiganaji. Jenga ufalme wako. Lazima utaje jina la mfalme kwa sauti ili upewe taji. Uzinduzi: Juni 30, 2026.",
          buttonText: "MFAHAMU KUFU",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_20260321_113436-ktAJOL2e0SS0pkTY6aPnn7aBKxr3pq.jpg",
          href: "/books/kufu",
          accentColor: "#F8B90D",
        },
        {
          id: "zattar",
          type: "book",
          tag: "ZATTAR: MWANAMFALME WA MWISHO",
          title: "ZATTAR",
          subtitle: "MWANAMFALME WA KONGO",
          description: "Wakati hatima ilipomkataa, aliamua kuuteka ulimwengu mzima. Zattar ndiye adui hatari zaidi katika ulimwengu wa Isolele.",
          buttonText: "MFAHAMU ZATTAR",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/e9c64c65-3717-4fe3-a391-885767df3303-LbjnMwCViF43pwErKmoFv7iGxQdCeQ.jpeg",
          href: "/books/zattar",
          accentColor: "#2E8B57",
        },
        {
          id: "amara",
          type: "book",
          tag: "AMARA: BINTI MFALME MPIGANAJI",
          title: "AMARA",
          subtitle: "BINTI MFALME ASIYETII",
          description: "Binti wa mfalme mwenye nguvu anayepigania haki. Katika ustaarabu wa Kongo, mabinti mfalme ni wapiganaji wa kulinda watu wao.",
          buttonText: "MFAHAMU AMARA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1173-wrVJYiZhuW6ZvCM0Xronsu544ccrqV.jpeg",
          href: "/#hero",
          accentColor: "#1E90B3",
        },
        {
          id: "zaiko",
          type: "book",
          tag: "ZAIKO: MFALME WA MITAA",
          title: "ZAIKO",
          subtitle: "HADITHI YA ZAIKO",
          description: "Alizaliwa North Kivu. Alijengwa Kinshasa. Zaiko alishinda hatima kwa chuma na utashi na kuwa mfalme anayeogopwa zaidi.",
          buttonText: "MFAHAMU ZAIKO",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1175-njlosetUOsqZszKylrOXsIRLw0l3s7.jpeg",
          href: "/books/zaiko",
          accentColor: "#2E8B57",
        }
      ]
    },

    es: {
      slides: [
        {
          id: "isolele",
          type: "book",
          tag: "BIENVENIDO A ISOLELE",
          title: "EL ELEGIDO",
          subtitle: "EL PRIMER UNIVERSO DE SUPERHÉROES NEGROS",
          description: "Isolele es un universo visionario nacido para restaurar el alma de la narrativa africana. Un imperio mitológico donde los héroes son elegidos por el destino.",
          buttonText: "EXPLORAR EL UNIVERSO",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Cover%20Book%202%20Isolele-QCEiRH2KJp3oFt4O31Qocqap3nLgiJ.jpg",
          href: "/books/isolele",
          accentColor: "#F6B800",
        },
        {
          id: "zaiire",
          type: "book",
          tag: "ZAIIRE: PRÍNCIPE DE KONGO",
          title: "ZAIIRE",
          subtitle: "EL COLLAR DEL DESTINO",
          description: "Hijo de Shango y Kimoya, Zaiire lleva dos mundos en su interior: el mortal de los reyes y el divino del poder ancestral.",
          buttonText: "DESCUBRIR A ZAIIRE",
          image: "/images/zaiire-cover-2026.webp",
          href: "/books/zaiire",
          accentColor: "#F6B800",
        },
        {
          id: "makanda",
          type: "book",
          tag: "LA DINASTÍA MAKANDA",
          title: "MAKANDA",
          subtitle: "LA DINASTÍA OCULTA",
          description: "Una civilización avanzada en el corazón de África que desapareció para proteger la Llama Sagrada, esperando al nuevo portador.",
          buttonText: "DESCUBRIR MAKANDA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/KIMOYA%20-%20THE%20RISING%20KANDAKE-kpNHOGXUp1l9A5z7uJ2Z4kI3v7e0ek.jpg",
          href: "/books/makanda",
          accentColor: "#C0392B",
        },
        {
          id: "bambula",
          type: "book",
          tag: "BAMBULA: HIJO DEL RITMO",
          title: "BAMBULA",
          subtitle: "EL TAMBOR SAGRADO",
          description: "Armado con el tambor sagrado, Bambula camina entre el mundo de los espíritus y el de los vivos para proteger la memoria africana.",
          buttonText: "DESCUBRIR BAMBULA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Bambula%201-UAlmQoZVy1GslUfmVvqc5bdDDdEQdX.jpg",
          href: "/books/bambula",
          accentColor: "#B3541E",
        },
        {
          id: "mokele",
          type: "book",
          tag: "MOKELE: DE LAS CALLES AL PODER",
          title: "MOKELE",
          subtitle: "LAS CALLES DE KINSHASA",
          description: "Nacido en la lucha, Mokele aprendió que la supervivencia lo es todo. Construyó un imperio de respeto en la selva de Kinshasa.",
          buttonText: "DESCUBRIR MOKELE",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Mokele.png-7sTyiUJYN8wJbiGll8YdVThtR4F8FT.jpeg",
          href: "/books/mokele",
          accentColor: "#4169E1",
        },
        {
          id: "kufu",
          type: "book",
          tag: "KUFU: JUEGO DE CARTAS",
          title: "KUFU",
          subtitle: "103 CARTAS. UNA CORONA.",
          description: "Reúne a tus guerreros. Construye tu reino. Solo hay una forma de ganar: pronunciar el nombre del rey en voz alta. Lanzamiento: 30 de junio de 2026.",
          buttonText: "DESCUBRIR KUFU",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_20260321_113436-ktAJOL2e0SS0pkTY6aPnn7aBKxr3pq.jpg",
          href: "/books/kufu",
          accentColor: "#F8B90D",
        },
        {
          id: "zattar",
          type: "book",
          tag: "ZATTAR: EL ÚLTIMO PRÍNCIPE",
          title: "ZATTAR",
          subtitle: "PRÍNCIPE DE KONGO",
          description: "Cuando el destino le negó un reino, decidió tomarlos todos. El villano más peligroso que desafió al universo entero.",
          buttonText: "DESCUBRIR ZATTAR",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/e9c64c65-3717-4fe3-a391-885767df3303-LbjnMwCViF43pwErKmoFv7iGxQdCeQ.jpeg",
          href: "/books/zattar",
          accentColor: "#2E8B57",
        },
        {
          id: "amara",
          type: "book",
          tag: "AMARA: LA PRINCESA REBELDE",
          title: "AMARA",
          subtitle: "GUERRERA DEL KONGO",
          description: "Hija de un rey pero guerrera por justicia. Amara desafía la tradición para liderar a su pueblo hacia la victoria.",
          buttonText: "DESCUBRIR AMARA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1173-wrVJYiZhuW6ZvCM0Xronsu544ccrqV.jpeg",
          href: "/#hero",
          accentColor: "#1E90B3",
        },
        {
          id: "zaiko",
          type: "book",
          tag: "ZAIKO: REY DE LAS CALLES",
          title: "ZAIKO",
          subtitle: "LA LEYENDA DE ZAIKO",
          description: "Forjado en Kivu del Norte y Kinshasa. Zaiko construyó el imperio más temido con voluntad de hierro y fuerza africana.",
          buttonText: "DESCUBRIR ZAIKO",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1175-njlosetUOsqZszKylrOXsIRLw0l3s7.jpeg",
          href: "/books/zaiko",
          accentColor: "#2E8B57",
        }
      ]
    },
    zu: {
      slides: [
        {
          id: "isolele",
          type: "book",
          tag: "WAMUKELEKILE E-ISOLELE",
          title: "OKHETHIWEYO",
          subtitle: "UMHLABA WOKUQALA WAMAQHAWE AMNYAMA ASE-AFRIKA",
          description:
            "I-Isolele wumbono womhlaba owazalelwa ukuvuselela umphefumulo wokuxoxwa kwezindaba zase-Afrika, umbuso wezinganekwane lapho amaqhawe akhethwa khona isiphetho, imibuso engakhohlwa, namandla okhokho aphila kuwo wonke amakhasi, zonke iziprofetho, nazo zonke izimpi. Wonke umntwana ofunda i-Isolele uzothola amaqhawe abukeka njengaye, akhuluma ulimi lwakhe, avikela umhlaba wakhe, futhi ahlonipha okhokho bakhe. Lokhu kwenzelwa isizukulwane esizayo samakhosi, amakhosikazi, amaqhawe, abasunguli, nabaxoxi bezindaba. I-ISOLELE wumhlaba wokuqala wamaqhawe amnyama ase-Afrika osuselwa efubeni le-Kongo yangempela, owakhiwe e-DRC futhi wabelwa umhlaba wonke.",
          buttonText: "HLOLA UMHLABA",
          image:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Cover%20Book%202%20Isolele-QCEiRH2KJp3oFt4O31Qocqap3nLgiJ.jpg",
          href: "/books/isolele",
          accentColor: "#F6B800",
        },
        {
          id: "zaiire",
          type: "book",
          tag: "U-ZAIIRE: INKOSANA YASE-KONGO",
          title: "U-ZAIIRE",
          subtitle: "UMGINTI WESIPHETHO",
          description:
            "U-Zaiire akazalwanga eyiqhawe. Uzalwe ekhethiwe. Indodana kaShango, inkosi yezulu, neNkosazana uKimoya, indlovukazi eyiqhawe yozalo lwenkosi yase-Kongo. U-Zaiire uthwele imihlaba emibili ngaphakathi kuye. Umhlaba wabantu wamakhosi, izimpi, nokuzidela. Kanye nomhlaba waphezulu wamandla okhokho, isiphetho somhlaba, namandla amadala kunanoma yimuphi umbuso.",
          buttonText: "THOLA U-ZAIIRE",
          image: "/images/zaiire-cover-2026.webp",
          href: "/books/zaiire",
          accentColor: "#F6B800",
        },
        {
          id: "makanda",
          type: "book",
          tag: "UZALO LUKA-MAKANDA - INCWADI I",
          title: "U-MAKANDA",
          subtitle: "UZALO OLUCASHILE",
          description:
            "Ekujuleni kwe-Central Africa kwakunempucuko umhlaba owawungahloselwe ukuyazi. Ephapheme ngokomoya. Ethuthukile kwezobuchwepheshe. Evikelwe yi-Sacred Flame. Lapho amabutho angaphandle efika ezofuna okwabo, ama-Makanda awayinganga. Anyamalala. Idolobha labo alizange lilahleke. Lalilindele lowo ozalelwe ukuphatha ilangabi futhi. Uzalo luka-Makanda wuchungechunge lwamahlaya amnyama lase-Afrika oluzalwe empucukweni yase-Kongo, umbuso ofihliwe osukela enhliziyweni ye-DRC.",
          buttonText: "THOLA U-MAKANDA",
          image:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/KIMOYA%20-%20THE%20RISING%20KANDAKE-kpNHOGXUp1l9A5z7uJ2Z4kI3v7e0ek.jpg",
          href: "/books/makanda",
          accentColor: "#C0392B",
        },
        {
          id: "bambula",
          type: "book",
          tag: "U-BAMBULA: INGANE YESIGQI",
          title: "U-BAMBULA",
          subtitle: "ISIGUBHU ESINGCWELE",
          description:
            "Ngaphambi kwamazwi, kwakunesigqi. U-Bambula kwakuyingane eyayizwa konke. Lapho izigubhu zithathwa kanti nezwe lithula, wagcina isigqi siphila ngaphakathi kuye. Ehlomile ngesigubhu esingcwele, uhamba phakathi kwezwe lomoya nelabaphilayo. Akalwi ukuze acebe. Uvikela ukuze akhumbule. U-Bambula uyiqhawe elimnyama lase-Afrika elisuselwa emasikweni omoya wase-Kongo, lapho isigubhu esingcwele sixhumanisa abaphilayo nokhokho.",
          buttonText: "THOLA U-BAMBULA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Bambula%201-UAlmQoZVy1GslUfmVvqc5bdDDdEQdX.jpg",
          href: "/books/bambula",
          accentColor: "#B3541E",
        },
        {
          id: "mokele",
          type: "book",
          tag: "U-MOKELE: KUSUKELA ENGANENI KUYA ENKOSINI",
          title: "U-MOKELE",
          subtitle: "KUSUKELA EZITALADINI ZASE-KINSHASA",
          description:
            "U-Mokele akazalwanga eyinkosi. Uzalelwe ekuhluphekeni. Izitaladi zase-Kinshasa zimfundisile ngaphambi kokuba isikole sikwenze lokho, lapho ukwethembeka kubuthakathaka, udlame luyinto ejwayelekile, kanti nokusinda kuyikho konke. Kusukela enganeni kuya kumhushuluzi kuye enkosini. Akha amandla, imali, nenhlonipho. E-Kinshasa, kungenzeka udliwe… Noma ube yisilo esidlayo. U-Mokele ngumlingiswa wamahlaya amnyama lase-Afrika ozalelwe ezitaladini zase-Kinshasa, e-DRC, lapho ukusinda kwakha imibuso.",
          buttonText: "THOLA U-MOKELE",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Mokele.png-7sTyiUJYN8wJbiGll8YdVThtR4F8FT.jpeg",
          href: "/books/mokele",
          accentColor: "#4169E1",
        },
        {
          id: "kufu",
          type: "book",
          tag: "I-KUFU: UMDLALO WEZINKADI WASE-AFRIKA",
          title: "I-KUFU",
          subtitle: "IZINKADI EZINGU-103. UMQSHELE OWODWA.",
          description:
            "Lona akuyona nje umdlalo wezinkadi. Kuyisiko. Qoqa amabutho akho. Yakha umbuso wakho. Hlula wonke umuntu etafuleni. Kodwa ukuze uthole umqhele kunendlela eyodwa kuphela yokuwina. Kumele uphakamise izwi lakho ubize igama lenkosi phezulu. Ngemuva kwalokho othile ufaka umginti ekhanda lakho. Hhayi ngesandla sakho. Kodwa ngesomunye. Ngoba inkosi yangempela ayigcotshwa iyodwa. I-KUFU kulapho ubukhosi base-Afrika buba yinto oyizwayo ezandleni zakho, oyizwayo ezwini lakho, n oyithwele entanyeni yakho. Wonke umdlalo wukugcotshwa. Wonke owinile uyinkosi. I-Kufu wumdlalo wokuqala wezinkadi wase-Afrika ohlanganisa amakhosi, amakhosikazi, namaqhawe ase-Afrika avela empucukweni yase-Kongo. Izinkadi ezingu-103. Umqhele owodwa. Kwethulwa ngoJuni 30, 2026.",
          buttonText: "THOLA I-KUFU",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_20260321_113436-ktAJOL2e0SS0pkTY6aPnn7aBKxr3pq.jpg",
          href: "/books/kufu",
          accentColor: "#F8B90D",
        },
        {
          id:"zattar",
          type: "book",
          tag: "U-ZATTAR: INKOSANA YOKUGCINA",
          title: "U-ZATTAR",
          subtitle: "INKOSANA YOKUGCINA YASE-KONGO",
          description:
            "Lapho Isiphetho Simncisha Umbuso Owodwa, Wanquma Ukuyithatha Yonke. Inkosana u-Zattar wazalelwa ukuzuza isihlalo sobukhosi sase-Bapindi. Kodwa lapho okhokho bekhetha omunye, okuthile ngaphakathi kuye akuzange kuphuke. Kwavutha amalangabi. Wafunda ngezimpi zokuqala nezesibili zase-Vegas, izinganekwane zokucekelwa phansi ezazamazamisa umhlaba ngaphambi kokuba azalwe. Lapho abanye bebona isixwayiso, u-Zattar wabona imephu. Waqala iMpi Yesithathu yase-Vegas. Hhayi ngenxa yobuhlanya. Hhayi ngenxa yobuhlungu. Kodwa ngenxa yokuthi wabuka yonke indawo yendawo yonke futhi wafika esiphethweni esisodwa: Inomnikazi. Futhi lowo mnikazi ngu-Zattar. Akakhethwanga. Ngakho-ke wakhetha indawo yonke esikhundleni salokho. U-Zattar uyisitha esimnyama sase-Afrika esiyingozi kakhulu kumahlaya, iNkosana yase-Bapindi eyenqaba isiphetho futhi yamemezela impi kuyo yonke indawo yonke.",
          buttonText: "THOLA U-ZATTAR",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/e9c64c65-3717-4fe3-a391-885767df3303-LbjnMwCViF43pwErKmoFv7iGxQdCeQ.jpeg",
          href: "/books/zattar",
          accentColor: "#2E8B57",
        },
        {
          id: "amara",
          type: "book",
          tag: "U-AMARA: INKOSAZANA EYISIHLWANE",
          title: "U-AMARA",
          subtitle: "INKOSAZANA EYISIHLWANE YASE-KONGO",
          description:
            "U-Amara uyinkosazana eyisihlwane yase-Kongo. Indodakazi enolaka yenkosi enamandla, uphikisana namasiko futhi ulwela ubulungiswa ezweni elizama ukumthulisa. Lapho umbuso wakhe usongelwa amabutho angaphandle, u-Amara uthatha izikhali ukuze avikele abantu bakhe futhi abuyise indawo yakhe efanele esihlalweni sobukhosi. U-Amara ngumlingiswa wamahlaya amnyama lase-Afrika ozalwe ozalweni lwenkosi lwempucuko yase-Kongo, lapho amakhosazana engekona nje kuphela izibalo zobuhle, kodwa engamaqhawe amiselwe ukuhola abantu bawo ekunqobeni.",
          buttonText: "THOLA U-AMARA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1173-wrVJYiZhuW6ZvCM0Xronsu544ccrqV.jpeg",
          href: "/#hero",
          accentColor: "#1E90B3",
        },
        {
          id: "zaiko",
          type: "book",
          tag: "U-ZAIKO: INKOSI YOKUGCINA YEZITALADI ZASE-KIVU",
          title: "U-ZAIKO",
          subtitle: "UMLANDO KA-ZAIKO",
          description:
            "Wazalwa e-North Kivu. Wakhiwa e-Kinshasa. U-Zaiko kwakungamele aphile. Kodwa ukusinda kwakungenele. Ezweni elibuswa amandla, imali, nokwesaba, usukela ezeni. Hhayi njengeqhawe. Kodwa njengamandla. Kanye nomfowabo, wakha umbuso owesatshwa kakhulu i-Kivu eyake yawazi. Awukho umqhele owanikezwa. Awukho isiphetho esabhalwa. Konke kwathathwa. Wonke umbuso wakhiwa phezu komlotha walabo abafika ngaphambili. Lona umlando wokuthi umuntu oyedwa waliphikisa kanjani isiphetho ngokwakhe futhi waqopha igama lakhe emlandweni wase-Afrika ngensimbi nangentando. U-Zaiko uyiqhawe lamahlaya amnyama lase-Afrika elizalwe e-North Kivu, e-DRC, lapho impi yakha khona inkosi eyesatshwa kakhulu izitaladi ezake yazazi.",
          buttonText: "THOLA U-ZAIKO",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1175-njlosetUOsqZszKylrOXsIRLw0l3s7.jpeg",
          href: "/books/zaiko",
          accentColor: "#2E8B57",
        }
      ]
    },

    xh: {
      slides: [
        {
          id: "isolele",
          type: "book",
          tag: "WAMKELEKILE E-ISOLELE",
          title: "ONYULIWEYO",
          subtitle: "INDALO YOKUQALA YAMAQHAWE AMNYAMA ASE-AFRIKA",
          description:
            "I-Isolele yindalo yombono eyazalelwa ukubuyisela umphefumulo wokubaliswa kwamabali ase-Afrika, ubukhosi basentsomini apho amaqhawe anyulwa sisiphetho. Imibuso engalibalekiyo namandla ezinyanya aphila kuwo onke amaphepha neziprofeto. Wonke umntwana ofunda i-Isolele uya kufumana amaqhawe afana naye, athetha ulwimi lwakhe, kwaye ahlonipha izinyanya zakhe. Le nto yenzelwe isizukulwane esizayo seekumkani, amagorha, nabaqambi bebali. I-ISOLELE yindalo yokuqala yamaqhawe amnyama ase-Afrika esekelwe kwilifa lokwenyani lase-Kongo, eyenziwe e-DRC yenzelwa umhlaba wonke.",
          buttonText: "PHANDA INDALO",
          image:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Cover%20Book%202%20Isolele-QCEiRH2KJp3oFt4O31Qocqap3nLgiJ.jpg",
          href: "/books/isolele",
          accentColor: "#F6B800",
        },
        {
          id: "zaiire",
          type: "book",
          tag: "U-ZAIIRE: INKOSANA YASE-KONGO",
          title: "U-ZAIIRE",
          subtitle: "INTLOKOMO YESIPHETHO",
          description:
            "U-Zaiire akazalwanga eliqhawe. Uzelwe enyuliwe. Unyana kaShango, inkosi yeendudumo, nenkosazana uKimoya, ukumkanikazi eliqhawe lozalo lwase-Kongo. U-Zaiire uphethe imihlaba emibini ngaphakathi kuye. Umhlaba wabantu weekumkani neemfazwe, nomhlaba wezinyanya onamandla amadala kunayo yonke imibuso.",
          buttonText: "FUMANA U-ZAIIRE",
          image: "/images/zaiire-cover-2026.webp",
          href: "/books/zaiire",
          accentColor: "#F6B800",
        },
        {
          id: "makanda",
          type: "book",
          tag: "UZALO LUKA-MAKANDA - INCWADI I",
          title: "U-MAKANDA",
          subtitle: "UZALO OLUFIHLIWEYO",
          description:
            "Ekujuleni kwe-Central Africa kwakukho impucuko umhlaba owawungamelanga kuyazi. Ephakamileyo ngokomoya kwaye ephambili ngezobuchwepheshe. Evikelwe yi-Sacred Flame. Xa amabutho angaphandle efika, ama-Makanda anyamalala ukukhusela imfihlo yawo. Uzalo luka-Makanda lusekelwe kwi-DRC, ubutyebi obufihliweyo bentliziyo ye-Afrika.",
          buttonText: "FUMANA U-MAKANDA",
          image:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/KIMOYA%20-%20THE%20RISING%20KANDAKE-kpNHOGXUp1l9A5z7uJ2Z4kI3v7e0ek.jpg",
          href: "/books/makanda",
          accentColor: "#C0392B",
        },
        {
          id: "bambula",
          type: "book",
          tag: "U-BAMBULA: UMNTWANA WESINGQI",
          title: "U-BAMBULA",
          subtitle: "IGUBU ELINGCWELE",
          description:
            "Exhobile ngegubu elingcwele, uBambula uhamba phakathi kwelizwe lemimoya nelabaphilayo. Akalwi ukuze atshabalalise, ukhusela ukuze isingqi somhlaba singaze sicime. Isithethe somoya wase-Kongo apho igubu lidibanisa abaphilayo nezinyanya.",
          buttonText: "FUMANA U-BAMBULA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Bambula%201-UAlmQoZVy1GslUfmVvqc5bdDDdEQdX.jpg",
          href: "/books/bambula",
          accentColor: "#B3541E",
        },
        {
          id: "mokele",
          type: "book",
          tag: "U-MOKELE: UKUSUKA EZITALATWENI",
          title: "U-MOKELE",
          subtitle: "IZITALATO ZASE-KINSHASA",
          description:
            "U-Mokele akazalwanga eyikumkani. Izitalato zase-Kinshasa zimfundise ukuba ukusinda yinto yonke. Wakha umbuso wakhe ngamandla nentlonipho kule jungle yasedolophini. E-Kinshasa, unokuba lixhoba... okanye ube likatshulange.",
          buttonText: "FUMANA U-MOKELE",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Mokele.png-7sTyiUJYN8wJbiGll8YdVThtR4F8FT.jpeg",
          href: "/books/mokele",
          accentColor: "#4169E1",
        },
        {
          id: "kufu",
          type: "book",
          tag: "I-KUFU: UMDLALO WAMAKHADI",
          title: "I-KUFU",
          subtitle: "AMAKHADI AYI-103. ISITHSABA ESINYE.",
          description:
            "Lo akulo mdlalo nje, sisithethe. Hlanganisa amagorha akho kwaye wakhe ubukhosi bakho. Ukuze uphumelele, kufuneka ubize igama lekumkani phezulu. Umdlalo wase-Afrika ophefumlelwe yimpucuko yase-Kongo. Uphehlelelo: 30 Juni 2026.",
          buttonText: "FUMANA I-KUFU",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_20260321_113436-ktAJOL2e0SS0pkTY6aPnn7aBKxr3pq.jpg",
          href: "/books/kufu",
          accentColor: "#F8B90D",
        },
        {
          id: "zattar",
          type: "book",
          tag: "U-ZATTAR: INKOSANA EWILEYO",
          title: "U-ZATTAR",
          subtitle: "INKOSANA YOKUGQIBELA YASE-KONGO",
          description:
            "Xa isiphetho simvimbe itrone, wagqiba kwelokuba ayithathe yonke indalo. U-Zattar lolona tshaba luyingozi kakhulu kwi-Isolele, inkosana evakalise imfazwe kwinyani uqobo lwayo.",
          buttonText: "FUMANA U-ZATTAR",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/e9c64c65-3717-4fe3-a391-885767df3303-LbjnMwCViF43pwErKmoFv7iGxQdCeQ.jpeg",
          href: "/books/zattar",
          accentColor: "#2E8B57",
        },
        {
          id: "amara",
          type: "book",
          tag: "U-AMARA: INKOSAZANA ELIQHAWE",
          title: "U-AMARA",
          subtitle: "INKOSAZANA ENGONCEDIYO",
          description:
            "Intombi yekumkani kodwa eliqhawe ngokhetho, uAmara ucela umngeni kwizithethe ukukhusela abantu bakhe. Kwimpucuko yase-Kongo, iinkosazana ngamagorha amiselwe ukoyisa.",
          buttonText: "FUMANA U-AMARA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1173-wrVJYiZhuW6ZvCM0Xronsu544ccrqV.jpeg",
          href: "/#hero",
          accentColor: "#1E90B3",
        },
        {
          id: "zaiko",
          type: "book",
          tag: "U-ZAIKO: INKOSI YEZITALATO ZASE-KIVU",
          title: "U-ZAIKO",
          subtitle: "IBALI LIKAZAIKO",
          description:
            "Wazalelwa e-North Kivu, wakhulela e-Kinshasa. U-Zaiko wakha ubukhosi oboyikekayo ngentsimbi nangentando yakhe. Ibali lase-Afrika lamandla nobugorha emva kokusinda ekufeni.",
          buttonText: "FUMANA U-ZAIKO",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1175-njlosetUOsqZszKylrOXsIRLw0l3s7.jpeg",
          href: "/books/zaiko",
          accentColor: "#2E8B57",
        }
      ]
    } 
};
