import type { HeroSlide } from "./types";

export const BOOK_HERO_SLIDE_VARIANTS = {
  enter: (direction: number) => ({
    x: direction > 0 ? "100%" : "-100%",
    opacity: 0,
  }),
  center: {
    x: 0,
    opacity: 1,
  },
  exit: (direction: number) => ({
    x: direction > 0 ? "-100%" : "100%",
    opacity: 0,
  }),
};

export const BOOK_HERO_BLUR_DATA_URL =
  "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAICAgIChsICQkJChAODwoQFwwTGB8WFBcUFRYaFxwpHhcYGRgaGBgSHBwcHhcYGhj/2wBDAQcHBwoIChMICQsMCggKGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBj/wAARCABkAGQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWm5ybnJ2eoqOkpaanqKmqsrO0tba2uLm6wsPExcbHyMnK0tPU1dbW2Nna4uPk5ebn6Onq8vP09fb2+Pn6/8QAHwEAAwEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlbaWmJmaoqOkpaanqKmqsrO0tba2uLm6wsPExcbHyMnK0tPU1dbW2Nna4uPk5ebn6Onq8vP09fb2+Pn6/9oAMBAAIRAxEAPwD3+iiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigD//Z";

export const bookHeroData: Record<string, { slides: HeroSlide[] }> = {
  en: {
    slides: [
      {
        id: "isolele",
        type: "book",
        tag: "WELCOME TO ISOLELE",
        title: "THE CHOSEN ONE",
        subtitle: "THE FIRST BLACK AFRICAN SUPERHERO UNIVERSE",
        description:
          "Isolele is a visionary universe born to restore the soul of African storytelling, a mythological empire where superheroes are chosen by destiny, kingdoms never forgotten, and ancestral power is alive in every page, every prophecy, every battle. Every child who reads Isolele will discover superheroes who look like them, speak their language, protect their land, and honor their ancestors. This is for the next generation of kings, queens, warriors, inventors, and storytellers. ISOLELE is the first Black African superhero universe rooted in authentic Kongo heritage, created in the DRC and built for the world.",
        buttonText: "EXPLORE THE UNIVERSE",
        image:
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Cover%20Book%202%20Isolele-QCEiRH2KJp3oFt4O31Qocqap3nLgiJ.jpg",
        href: "/books/isolele",
        accentColor: "#F6B800",
      },
      {
        id: "zaiire",
        type: "book",
        tag: "ZAIIRE: PRINCE OF KONGO",
        title: "ZAIIRE",
        subtitle: "THE NECKLACE OF DESTINY",
        description:
          "Zaiire is not born a hero. He is born chosen. Son of Shango, the divine lord of thunder, and Princess Kimoya, a warrior queen of the Kongo royal bloodline, Zaiire carries two worlds inside him. The mortal world of kings, wars, and sacrifice. And the divine world of ancestral power, cosmic destiny, and forces older than any kingdom.",
        buttonText: "DISCOVER ZAIIRE",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG-20260308-WA0059-75yxyGjuDt9hhqXF6obymfG8BpNLz4.jpg",
        href: "/books/zaiire",
        accentColor: "#F6B800",
      },
      {
        id: "makanda",
        type: "book",
        tag: "THE MAKANDA DYNASTY - BOOK I",
        title: "MAKANDA",
        subtitle: "THE HIDDEN DYNASTY",
        description:
          "Deep within Central Africa existed a civilization the world was never meant to know about. Spiritually awakened. Technologically advanced. Protected by the Sacred Flame. When outside forces came for what was theirs, the Makanda did not fall. They disappeared. Their city was never lost. It was waiting for the one born to carry the flame again. The Makanda Dynasty is a Black African comic series born from Kongo civilization, a hidden empire rising from the heart of the DRC.",
        buttonText: "DISCOVER MAKANDA",
        image:
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/KIMOYA%20-%20THE%20RISING%20KANDAKE-kpNHOGXUp1l9A5z7uJ2Z4kI3v7e0ek.jpg",
        href: "/books/makanda",
        accentColor: "#C0392B",
      },
      {
        id: "bambula",
        type: "book",
        tag: "BAMBULA: CHILD OF RHYTHM",
        title: "BAMBULA",
        subtitle: "THE SACRED DRUM",
        description:
          "Before words, there was rhythm. Bambula was the child who heard everything. When the drums were taken and the land went silent, he kept the rhythm alive inside him. Armed with the sacred drum, he walks between the spirit world and the living. He does not fight to destroy. He protects to remember. Bambula is a Black African superhero rooted in Kongo spiritual tradition, where the sacred drum connects the living to the ancestors.",
        buttonText: "DISCOVER BAMBULA",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Bambula%201-UAlmQoZVy1GslUfmVvqc5bdDDdEQdX.jpg",
        href: "/books/bambula",
        accentColor: "#B3541E",
      },
      {
        id: "mokele",
        type: "book",
        tag: "MOKELE: FROM CHILD TO LORD",
        title: "MOKELE",
        subtitle: "FROM THE STREETS OF KINSHASA",
        description:
          "Mokele is not born a king. He is born into struggle. The streets of Kinshasa teach him before school ever could, where loyalty is fragile, violence is normal, and survival is everything. From child to hustler to lord. He builds power, money, and respect. In Kinshasa, you either get eaten… Or you become the predator. Mokele is a Black African comic character born in the streets of Kinshasa, DRC, where survival builds empires.",
        buttonText: "DISCOVER MOKELE",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Mokele.png-7sTyiUJYN8wJbiGll8YdVThtR4F8FT.jpeg",
        href: "/books/mokele",
        accentColor: "#4169E1",
      },
      {
        id: "kufu",
        type: "book",
        tag: "KUFU: PAN-AFRICAN CARD GAME",
        title: "KUFU",
        subtitle: "103 CARDS. ONE CROWN.",
        description:
          "This is not just a card game. It is a ceremony. Gather your warriors. Build your kingdom. Outplay every opponent at the table. But to claim the crown there is only one way to win. You must raise your voice and speak the name of the king out loud. Then someone places the necklace over your head. Not by your own hand. By another. Because a true king is not crowned alone. KUFU is where African royalty becomes something you feel in your hands, hear in your voice, and carry around your neck. Every game is a coronation. Every winner is a king. Kufu is the first Pan-African card game featuring African kings, queens, and warriors from the Kongo civilization. 103 cards. One crown. Launching June 30, 2026.",
        buttonText: "DISCOVER KUFU",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_20260321_113436-ktAJOL2e0SS0pkTY6aPnn7aBKxr3pq.jpg",
        href: "/books/kufu",
        accentColor: "#F8B90D",
      },
      {
        id:"zattar",
        type: "book",
        tag: "ZATTAR: THE LAST PRINCE",
        title: "ZATTAR",
        subtitle: "THE LAST PRINCE OF KONGO",
        description:
          "When Destiny Refused Him One Kingdom, He Decided to Take Them All. Prince Zattar was born to inherit the throne of Bapindi. But when the Ancestors chose another, something inside him did not break. It ignited. He studied the First and Second Wars of Vegas, legends of devastation that shook the world before he was even born. Where others saw warning, Zattar saw a map. He started the Third War of Vegas. Not out of madness. Not out of pain. But because he looked at the entire universe and reached one conclusion: It belongs to someone. And that someone is Zattar. He was not chosen. So he chose the universe instead. Zattar is the most dangerous Black African villain in comics, a Prince of Bapindi who refused destiny and declared war on the entire universe.",
        buttonText: "DISCOVER ZATTAR",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/e9c64c65-3717-4fe3-a391-885767df3303-LbjnMwCViF43pwErKmoFv7iGxQdCeQ.jpeg",
        href: "/books/zattar",
        accentColor: "#2E8B57",
      },
      {
        id: "amara",
        type: "book",
        tag: "AMARA: THE REBEL PRINCESS",
        title: "AMARA",
        subtitle: "THE REBEL PRINCESS OF KONGO",
        description:
          "Amara is a rebel princess of Kongo. The fierce daughter of a powerful king, she defies tradition and fights for justice in a world that tries to silence her. When her kingdom is threatened by external forces, Amara takes up arms to protect her people and reclaim her rightful place on the throne. Amara is a Black African comic character born from the royal bloodline of Kongo civilization, where princesses are not just figures of beauty, but warriors destined to lead their people to victory.",
        buttonText: "DISCOVER AMARA",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1173-wrVJYiZhuW6ZvCM0Xronsu544ccrqV.jpeg",
        href: "/#hero",
        accentColor: "#1E90B3",
      },
      {
        id: "zaiko",
        type: "book",
        tag: "ZAIKO: LAST KING OF THE STREETS OF KIVUS",
        title: "ZAIKO",
        subtitle: "THE LEGEND OF ZAIKO",
        description:
          "Born in North Kivu. Forged in Kinshasa. Zaiko was never meant to survive. But survival was never enough. In a world ruled by power, money, and fear, he rises from nothing. Not as a hero. But as a force. With his brother, he builds the most feared empire the Kivus have ever known. No crown was given. No destiny was written. Everything was taken. Every empire built from the ashes of those who came before. This is the legend of how one man defied fate itself and carved his name into African history with iron and will. Zaiko is a Black African comic hero born in North Kivu, DRC, where war forged the most feared king the streets have ever known.",
        buttonText: "DISCOVER ZAIKO",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1175-njlosetUOsqZszKylrOXsIRLw0l3s7.jpeg",
        href: "/books/zaiko",
        accentColor: "#2E8B57",
      }
    ]
  },
  
  fr:{
    slides: [
      {
        id: "isolele",
        type: "book",
        tag: "BIENVENUE À ISOLELE",
        title: "L'ÉLU",
        subtitle: "LE PREMIER UNIVERS DE SUPER-HÉROS NOIRS AFRICAINS",
        description:
          "Isolele est un univers visionnaire né pour restaurer l'âme du récit africain, un empire mythologique où les super-héros sont choisis par le destin, les royaumes jamais oubliés, et le pouvoir ancestral vivant à chaque page, chaque prophétie, chaque bataille. Chaque enfant qui lira Isolele découvrira des super-héros qui lui ressemblent, parlent sa langue, protègent sa terre et honorent ses ancêtres. Ceci est pour la prochaine génération de rois, reines, guerriers, inventeurs et conteurs. ISOLELE est le premier univers de super-héros noirs africains ancré dans l'héritage authentique du Kongo, créé en RDC et construit pour le monde.",
        buttonText: "EXPLORER L'UNIVERS",
        image:
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Cover%20Book%202%20Isolele-QCEiRH2KJp3oFt4O31Qocqap3nLgiJ.jpg",
        href: "/books/isolele",
        accentColor: "#F6B800",
      },
      {
        id: "zaiire",
        type: "book",
        tag: "ZAIÏRE : PRINCE DU KONGO",
        title: "ZAIÏRE",
        subtitle: "LE COLLIER DU DESTIN",
        description:
          "Zaiïre n'est pas né héros. Il est né élu. Fils de Shango, le seigneur divin du tonnerre, et de la princesse Kimoya, une reine guerrière de la lignée royale du Kongo, Zaiïre porte deux mondes en lui. Le monde mortel des rois, des guerres et des sacrifices. Et le monde divin du pouvoir ancestral, du destin cosmique et des forces plus anciennes que n'importe quel royaume.",
        buttonText: "DÉCOUVRIR ZAIÏRE",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG-20260308-WA0059-75yxyGjuDt9hhqXF6obymfG8BpNLz4.jpg",
        href: "/books/zaiire",
        accentColor: "#F6B800",
      },
      {
        id: "makanda",
        type: "book",
        tag: "LA DYNASTIE MAKANDA - TOME I",
        title: "MAKANDA",
        subtitle: "LA DYNASTIE CACHÉE",
        description:
          "Au cœur de l'Afrique centrale existait une civilisation que le monde n'était jamais censé connaître. Spirituellement éveillée. Technologiquement avancée. Protégée par la Flamme Sacrée. Lorsque des forces extérieures sont venues prendre ce qui leur appartenait, les Makanda ne sont pas tombés. Ils ont disparu. Leur cité n'a jamais été perdue. Elle attendait celui né pour porter à nouveau la flamme. La Dynastie Makanda est une série de bandes dessinées africaines noires née de la civilisation Kongo, un empire caché surgissant du cœur de la RDC.",
        buttonText: "DÉCOUVRIR MAKANDA",
        image:
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/KIMOYA%20-%20THE%20RISING%20KANDAKE-kpNHOGXUp1l9A5z7uJ2Z4kI3v7e0ek.jpg",
        href: "/books/makanda",
        accentColor: "#C0392B",
      },
      {
        id: "bambula",
        type: "book",
        tag: "BAMBULA : L'ENFANT DU RYTHME",
        title: "BAMBULA",
        subtitle: "LE TAMBOUR SACRÉ",
        description:
          "Avant les mots, il y avait le rythme. Bambula était l'enfant qui entendait tout. Quand les tambours furent confisqués et que la terre devint silencieuse, il garda le rythme vivant en lui. Armé du tambour sacré, il marche entre le monde des esprits et celui des vivants. Il ne se bat pas pour détruire. Il protège pour se souvenir. Bambula est un super-héros noir africain ancré dans la tradition spirituelle Kongo, où le tambour sacré relie les vivants aux ancêtres.",
        buttonText: "DÉCOUVRIR BAMBULA",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Bambula%201-UAlmQoZVy1GslUfmVvqc5bdDDdEQdX.jpg",
        href: "/books/bambula",
        accentColor: "#B3541E",
      },
      {
        id: "mokele",
        type: "book",
        tag: "MOKELE : DE L'ENFANT AU SEIGNEUR",
        title: "MOKELE",
        subtitle: "DES RUES DE KINSHASA",
        description:
          "Mokele n'est pas né roi. Il est né dans la lutte. Les rues de Kinshasa lui ont appris la vie bien avant l'école, là où la loyauté est fragile, la violence normale et la survie primordiale. D'enfant à débrouillard puis à seigneur. Il bâtit le pouvoir, l'argent et le respect. À Kinshasa, soit on se fait manger… soit on devient le prédateur. Mokele est un personnage de bande dessinée africaine noire né dans les rues de Kinshasa, en RDC, où la survie bâtit des empires.",
        buttonText: "DÉCOUVRIR MOKELE",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Mokele.png-7sTyiUJYN8wJbiGll8YdVThtR4F8FT.jpeg",
        href: "/books/mokele",
        accentColor: "#4169E1",
      },
      {
        id: "kufu",
        type: "book",
        tag: "KUFU : JEU DE CARTES PANAFRICAIN",
        title: "KUFU",
        subtitle: "103 CARTES. UNE COURONNE.",
        description:
          "Ceci n'est pas qu'un jeu de cartes. C'est une cérémonie. Rassemblez vos guerriers. Bâtissez votre royaume. Surpassez chaque adversaire à la table. Mais pour réclamer la couronne, il n'y a qu'une seule façon de gagner. Vous devez élever la voix et prononcer le nom du roi à haute voix. Alors quelqu'un place le collier sur votre tête. Pas de votre propre main. Par une autre. Car un vrai roi n'est pas couronné seul. KUFU est là où la royauté africaine devient quelque chose que l'on ressent dans ses mains, que l'on entend dans sa voix et que l'on porte autour du cou. Chaque partie est un couronnement. Chaque gagnant est un roi. Kufu est le premier jeu de cartes panafricain mettant en scène des rois, des reines et des guerriers africains de la civilisation Kongo. 103 cartes. Une couronne. Lancement le 30 juin 2026.",
        buttonText: "DÉCOUVRIR KUFU",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_20260321_113436-ktAJOL2e0SS0pkTY6aPnn7aBKxr3pq.jpg",
        href: "/books/kufu",
        accentColor: "#F8B90D",
      },
      {
        id:"zattar",
        type: "book",
        tag: "ZATTAR : LE DERNIER PRINCE",
        title: "ZATTAR",
        subtitle: "LE DERNIER PRINCE DU KONGO",
        description:
          "Quand le Destin lui a refusé un royaume, il a décidé de tous les prendre. Le Prince Zattar était né pour hériter du trône de Bapindi. Mais quand les Ancêtres en ont choisi un autre, quelque chose en lui ne s'est pas brisé. Ça s'est enflammé. Il a étudié les Première et Seconde Guerres de Vegas, des légendes de dévastation qui ont secoué le monde avant même sa naissance. Là où les autres voyaient un avertissement, Zattar a vu une carte. Il a déclenché la Troisième Guerre de Vegas. Pas par folie. Pas par douleur. Mais parce qu'il a regardé l'univers entier et est arrivé à une conclusion : il appartient à quelqu'un. Et ce quelqu'un, c'est Zattar. Il n'a pas été choisi. Alors il a choisi l'univers à la place. Zattar est le méchant noir africain le plus dangereux de la bande dessinée, un prince de Bapindi qui a refusé le destin et déclaré la guerre à l'univers entier.",
        buttonText: "DÉCOUVRIR ZATTAR",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/e9c64c65-3717-4fe3-a391-885767df3303-LbjnMwCViF43pwErKmoFv7iGxQdCeQ.jpeg",
        href: "/books/zattar",
        accentColor: "#2E8B57",
      },
      {
        id: "amara",
        type: "book",
        tag: "AMARA : LA PRINCESSE REBELLE",
        title: "AMARA",
        subtitle: "LA PRINCESSE REBELLE DU KONGO",
        description:
          "Amara est une princesse rebelle du Kongo. Fille farouche d'un roi puissant, elle défie la tradition et se bat pour la justice dans un monde qui tente de la faire taire. Lorsque son royaume est menacé par des forces extérieures, Amara prend les armes pour protéger son peuple et réclamer sa place légitime sur le trône. Amara est un personnage de bande dessinée africaine noire née de la lignée royale de la civilisation Kongo, où les princesses ne sont pas seulement des figures de beauté, mais des guerrières destinées à mener leur peuple à la victoire.",
        buttonText: "DÉCOUVRIR AMARA",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1173-wrVJYiZhuW6ZvCM0Xronsu544ccrqV.jpeg",
        href: "/#hero",
        accentColor: "#1E90B3",
      },
      {
        id: "zaiko",
        type: "book",
        tag: "ZAIKO : LE DERNIER ROI DES RUES DU KIVU",
        title: "ZAIKO",
        subtitle: "LA LÉGENDE DE ZAIKO",
        description:
          "Né au Nord-Kivu. Forgé à Kinshasa. Zaiko n'était jamais censé survivre. Mais survivre n'était pas assez. Dans un monde régi par le pouvoir, l'argent et la peur, il s'élève de rien. Pas comme un héros. Mais comme une force. Avec son frère, il bâtit l'empire le plus craint que les Kivus aient jamais connu. Aucune couronne n'a été donnée. Aucun destin n'a été écrit. Tout a été pris. Chaque empire bâti sur les cendres de ceux qui l'ont précédé. C'est la légende de la façon dont un homme a défié le sort lui-même et a gravé son nom dans l'histoire africaine avec du fer et de la volonté. Zaiko est un héros de bande dessinée africaine noire né au Nord-Kivu, en RDC, où la guerre a forgé le roi le plus craint que les rues aient jamais connu.",
        buttonText: "DÉCOUVRIR ZAIKO",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1175-njlosetUOsqZszKylrOXsIRLw0l3s7.jpeg",
        href: "/books/zaiko",
        accentColor: "#2E8B57",
      }
    ]
  },

  
    ln: {
      slides: [
        {
          id: "isolele",
          type: "book",
          tag: "BOYEI BOLAMU NA ISOLELE",
          title: "MOPONAMI",
          subtitle: "MOKILI YA LIBOSO YA BA SUPER-HÉROS YA AFRIKA",
          description: "Isolele ezali bokonzi ya kala epai ba super-héros baponami na likambo ya lola. Mwana nyonso oyo akotanga Isolele akomona ba super-héros oyo bafani na ye mpe bakumisaka bankoko na ye. Esalami na RDC mpo na mokili mobimba.",
          buttonText: "KOTA NA MOKILI OYO",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Cover%20Book%202%20Isolele-QCEiRH2KJp3oFt4O31Qocqap3nLgiJ.jpg",
          href: "/books/isolele",
          accentColor: "#F6B800",
        },
        {
          id: "zaiire",
          type: "book",
          tag: "ZAIIRE : MWANA-KONZI YA KONGO",
          title: "ZAIIRE",
          subtitle: "ELOKO YA MOTEMA YA LIKAMBO YA LOLA",
          description: "Zaiïre abotami moponami. Mwana ya Shango mpe Princess Kimoya, amemi mikili mibale na kati na ye: mokili ya bato mpe nguya ya bankoko.",
          buttonText: "YREBA ZAIIRE",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG-20260308-WA0059-75yxyGjuDt9hhqXF6obymfG8BpNLz4.jpg",
          href: "/books/zaiire",
          accentColor: "#F6B800",
        },
        {
          id: "makanda",
          type: "book",
          tag: "DYNASTIE MAKANDA",
          title: "MAKANDA",
          subtitle: "BOKONZI EBOMBAMA",
          description: "Na kati ya Afrika, bokonzi moko ya mayele makasi ebombamaki mpo na kobatela munda ya bule. Basengelaki kozela moponami mpo na kopelisa munda yango lisusu.",
          buttonText: "YREBA MAKANDA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/KIMOYA%20-%20THE%20RISING%20KANDAKE-kpNHOGXUp1l9A5z7uJ2Z4kI3v7e0ek.jpg",
          href: "/books/makanda",
          accentColor: "#C0392B",
        },
        {
          id: "bambula",
          type: "book",
          tag: "BAMBULA : MWANA YA MIZIKI",
          title: "BAMBULA",
          subtitle: "LOKOLE YA BULE",
          description: "Na lokole na ye ya bule, Bambula atambolaka kati na mokili ya milimo mpe ya bato. Abundaka mpo na kobebisa te, kasi mpo na kobatela mimeseno ya bankoko.",
          buttonText: "YREBA BAMBULA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Bambula%201-UAlmQoZVy1GslUfmVvqc5bdDDdEQdX.jpg",
          href: "/books/bambula",
          accentColor: "#B3541E",
        },
        {
          id: "mokele",
          type: "book",
          tag: "MOKELE : MOKONZI YA BALABALA",
          title: "MOKELE",
          subtitle: "BALABALA YA KINSHASA",
          description: "Balabala ya Kinshasa eteyi ye bomoi yambo ya kelasi. Kobanda mwana ya moke tii na kokoma nkolo mokili, amonisi ete na Kinshasa, soki ozali mayele te, bakoliya yo.",
          buttonText: "YREBA MOKELE",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Mokele.png-7sTyiUJYN8wJbiGll8YdVThtR4F8FT.jpeg",
          href: "/books/mokele",
          accentColor: "#4169E1",
        },
        {
          id: "kufu",
          type: "book",
          tag: "KUFU : MASANO YA CARTES",
          title: "KUFU",
          subtitle: "103 CARTES. MOTOLE MOKO.",
          description: "Oyo ezali kaka lisano te, ezali feti ya bokonzi. Tonga bokonzi na yo mpe longola nkombo ya mokonzi na mongongo makasi mpo na kozwa motole.",
          buttonText: "YREBA KUFU",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_20260321_113436-ktAJOL2e0SS0pkTY6aPnn7aBKxr3pq.jpg",
          href: "/books/kufu",
          accentColor: "#F8B90D",
        },
        {
          id: "zattar",
          type: "book",
          tag: "ZATTAR : PRINCE YA MBANDA",
          title: "ZATTAR",
          subtitle: "MWANA-KONZI YA NSUKA YA KONGO",
          description: "Lokola bapesaki ye bokonzi te, azwi mokano ya kozwa mokili mobimba na makasi. Zattar azali monguna ya mabe koleka na lisolo ya Isolele.",
          buttonText: "YREBA ZATTAR",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/e9c64c65-3717-4fe3-a391-885767df3303-LbjnMwCViF43pwErKmoFv7iGxQdCeQ.jpeg",
          href: "/books/zattar",
          accentColor: "#2E8B57",
        },
        {
          id: "amara",
          type: "book",
          tag: "AMARA : MWANA-KONZI YA BITUMBA",
          title: "AMARA",
          subtitle: "PRINCESSE REBELLE",
          description: "Mwana ya mokonzi oyo aboyi mimeseno ya pamba. Amara azali mwanamoke ya bitumba oyo atelemeli mbeba nyonso mpo na kobatela bato na ye.",
          buttonText: "YREBA AMARA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1173-wrVJYiZhuW6ZvCM0Xronsu544ccrqV.jpeg",
          href: "/#hero",
          accentColor: "#1E90B3",
        },
        {
          id: "zaiko",
          type: "book",
          tag: "ZAIKO : MOKONZI YA KIVU",
          title: "ZAIKO",
          subtitle: "LISOLO YA ZAIKO",
          description: "Abotami na Nord-Kivu, akoli na Kinshasa. Zaiko azwi nkombo na ye na bitumba mpe na makila. Azali moko ya bato ya mabe oyo balekisa ndelo na nguya.",
          buttonText: "YREBA ZAIKO",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1175-njlosetUOsqZszKylrOXsIRLw0l3s7.jpeg",
          href: "/books/zaiko",
          accentColor: "#2E8B57",
        }
      ]
    },

    sw: {
      slides: [
        {
          id: "isolele",
          type: "book",
          tag: "KARIBU ISOLELE",
          title: "MTEULE",
          subtitle: "ULIMWENGU WA KWANZA WA MASHUJAA WEUSI",
          description: "Isolele ni milki ya kihadithi ambapo mashujaa huchaguliwa na hatima kurejesha roho ya hadithi za Kiafrika. Kila mtoto atagundua mashujaa wanaofanana naye.",
          buttonText: "GUNDUA ULIMWENGU",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Cover%20Book%202%20Isolele-QCEiRH2KJp3oFt4O31Qocqap3nLgiJ.jpg",
          href: "/books/isolele",
          accentColor: "#F6B800",
        },
        {
          id: "zaiire",
          type: "book",
          tag: "ZAIIRE: MWANAMFALME WA KONGO",
          title: "ZAIIRE",
          subtitle: "MKUFU WA HATIMA",
          description: "Zaiire hakuzaliwa shujaa, alizaliwa mteule. Mwana wa Shango na Princess Kimoya, amebeba ulimwengu wa binadamu na nguvu za mababu.",
          buttonText: "MFAHAMU ZAIIRE",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG-20260308-WA0059-75yxyGjuDt9hhqXF6obymfG8BpNLz4.jpg",
          href: "/books/zaiire",
          accentColor: "#F6B800",
        },
        {
          id: "makanda",
          type: "book",
          tag: "ENZI YA MAKANDA",
          title: "MAKANDA",
          subtitle: "ENZI ILIYOFICHWA",
          description: "Ustaarabu wa siri katikati ya Afrika. Walipofatwa na maadui, Makanda walitoweka kulinda Moto Mtakatifu wakingoja mbeba moto mpya.",
          buttonText: "MFAHAMU MAKANDA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/KIMOYA%20-%20THE%20RISING%20KANDAKE-kpNHOGXUp1l9A5z7uJ2Z4kI3v7e0ek.jpg",
          href: "/books/makanda",
          accentColor: "#C0392B",
        },
        {
          id: "bambula",
          type: "book",
          tag: "BAMBULA: MTOTO WA MDUNDO",
          title: "BAMBULA",
          subtitle: "NGOMA TAKATIFU",
          description: "Akiwa na ngoma takatifu, Bambula anatembea kati ya ulimwengu wa roho na walio hai ili kulinda kumbukumbu za mababu.",
          buttonText: "MFAHAMU BAMBULA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Bambula%201-UAlmQoZVy1GslUfmVvqc5bdDDdEQdX.jpg",
          href: "/books/bambula",
          accentColor: "#B3541E",
        },
        {
          id: "mokele",
          type: "book",
          tag: "MOKELE: KUTOKA MITAANI",
          title: "MOKELE",
          subtitle: "MITAA YA KINSHASA",
          description: "Mokele hakuzaliwa mfalme. Mitaa ya Kinshasa ilimfundisha kuishi. Alijenga himaya yake kwa nguvu na heshima katika mji usiokuwa na huruma.",
          buttonText: "MFAHAMU MOKELE",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Mokele.png-7sTyiUJYN8wJbiGll8YdVThtR4F8FT.jpeg",
          href: "/books/mokele",
          accentColor: "#4169E1",
        },
        {
          id: "kufu",
          type: "book",
          tag: "KUFU: MCHEZO WA KADI",
          title: "KUFU",
          subtitle: "KADI 103. TAJI MOJA.",
          description: "Mkusanyiko wa wapiganaji. Jenga ufalme wako. Lazima utaje jina la mfalme kwa sauti ili upewe taji. Uzinduzi: Juni 30, 2026.",
          buttonText: "MFAHAMU KUFU",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_20260321_113436-ktAJOL2e0SS0pkTY6aPnn7aBKxr3pq.jpg",
          href: "/books/kufu",
          accentColor: "#F8B90D",
        },
        {
          id: "zattar",
          type: "book",
          tag: "ZATTAR: MWANAMFALME WA MWISHO",
          title: "ZATTAR",
          subtitle: "MWANAMFALME WA KONGO",
          description: "Wakati hatima ilipomkataa, aliamua kuuteka ulimwengu mzima. Zattar ndiye adui hatari zaidi katika ulimwengu wa Isolele.",
          buttonText: "MFAHAMU ZATTAR",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/e9c64c65-3717-4fe3-a391-885767df3303-LbjnMwCViF43pwErKmoFv7iGxQdCeQ.jpeg",
          href: "/books/zattar",
          accentColor: "#2E8B57",
        },
        {
          id: "amara",
          type: "book",
          tag: "AMARA: BINTI MFALME MPIGANAJI",
          title: "AMARA",
          subtitle: "BINTI MFALME ASIYETII",
          description: "Binti wa mfalme mwenye nguvu anayepigania haki. Katika ustaarabu wa Kongo, mabinti mfalme ni wapiganaji wa kulinda watu wao.",
          buttonText: "MFAHAMU AMARA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1173-wrVJYiZhuW6ZvCM0Xronsu544ccrqV.jpeg",
          href: "/#hero",
          accentColor: "#1E90B3",
        },
        {
          id: "zaiko",
          type: "book",
          tag: "ZAIKO: MFALME WA MITAA",
          title: "ZAIKO",
          subtitle: "HADITHI YA ZAIKO",
          description: "Alizaliwa North Kivu. Alijengwa Kinshasa. Zaiko alishinda hatima kwa chuma na utashi na kuwa mfalme anayeogopwa zaidi.",
          buttonText: "MFAHAMU ZAIKO",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1175-njlosetUOsqZszKylrOXsIRLw0l3s7.jpeg",
          href: "/books/zaiko",
          accentColor: "#2E8B57",
        }
      ]
    },

    es: {
      slides: [
        {
          id: "isolele",
          type: "book",
          tag: "BIENVENIDO A ISOLELE",
          title: "EL ELEGIDO",
          subtitle: "EL PRIMER UNIVERSO DE SUPERHÉROES NEGROS",
          description: "Isolele es un universo visionario nacido para restaurar el alma de la narrativa africana. Un imperio mitológico donde los héroes son elegidos por el destino.",
          buttonText: "EXPLORAR EL UNIVERSO",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Cover%20Book%202%20Isolele-QCEiRH2KJp3oFt4O31Qocqap3nLgiJ.jpg",
          href: "/books/isolele",
          accentColor: "#F6B800",
        },
        {
          id: "zaiire",
          type: "book",
          tag: "ZAIIRE: PRÍNCIPE DE KONGO",
          title: "ZAIIRE",
          subtitle: "EL COLLAR DEL DESTINO",
          description: "Hijo de Shango y Kimoya, Zaiire lleva dos mundos en su interior: el mortal de los reyes y el divino del poder ancestral.",
          buttonText: "DESCUBRIR A ZAIIRE",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG-20260308-WA0059-75yxyGjuDt9hhqXF6obymfG8BpNLz4.jpg",
          href: "/books/zaiire",
          accentColor: "#F6B800",
        },
        {
          id: "makanda",
          type: "book",
          tag: "LA DINASTÍA MAKANDA",
          title: "MAKANDA",
          subtitle: "LA DINASTÍA OCULTA",
          description: "Una civilización avanzada en el corazón de África que desapareció para proteger la Llama Sagrada, esperando al nuevo portador.",
          buttonText: "DESCUBRIR MAKANDA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/KIMOYA%20-%20THE%20RISING%20KANDAKE-kpNHOGXUp1l9A5z7uJ2Z4kI3v7e0ek.jpg",
          href: "/books/makanda",
          accentColor: "#C0392B",
        },
        {
          id: "bambula",
          type: "book",
          tag: "BAMBULA: HIJO DEL RITMO",
          title: "BAMBULA",
          subtitle: "EL TAMBOR SAGRADO",
          description: "Armado con el tambor sagrado, Bambula camina entre el mundo de los espíritus y el de los vivos para proteger la memoria africana.",
          buttonText: "DESCUBRIR BAMBULA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Bambula%201-UAlmQoZVy1GslUfmVvqc5bdDDdEQdX.jpg",
          href: "/books/bambula",
          accentColor: "#B3541E",
        },
        {
          id: "mokele",
          type: "book",
          tag: "MOKELE: DE LAS CALLES AL PODER",
          title: "MOKELE",
          subtitle: "LAS CALLES DE KINSHASA",
          description: "Nacido en la lucha, Mokele aprendió que la supervivencia lo es todo. Construyó un imperio de respeto en la selva de Kinshasa.",
          buttonText: "DESCUBRIR MOKELE",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Mokele.png-7sTyiUJYN8wJbiGll8YdVThtR4F8FT.jpeg",
          href: "/books/mokele",
          accentColor: "#4169E1",
        },
        {
          id: "kufu",
          type: "book",
          tag: "KUFU: JUEGO DE CARTAS",
          title: "KUFU",
          subtitle: "103 CARTAS. UNA CORONA.",
          description: "Reúne a tus guerreros. Construye tu reino. Solo hay una forma de ganar: pronunciar el nombre del rey en voz alta. Lanzamiento: 30 de junio de 2026.",
          buttonText: "DESCUBRIR KUFU",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_20260321_113436-ktAJOL2e0SS0pkTY6aPnn7aBKxr3pq.jpg",
          href: "/books/kufu",
          accentColor: "#F8B90D",
        },
        {
          id: "zattar",
          type: "book",
          tag: "ZATTAR: EL ÚLTIMO PRÍNCIPE",
          title: "ZATTAR",
          subtitle: "PRÍNCIPE DE KONGO",
          description: "Cuando el destino le negó un reino, decidió tomarlos todos. El villano más peligroso que desafió al universo entero.",
          buttonText: "DESCUBRIR ZATTAR",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/e9c64c65-3717-4fe3-a391-885767df3303-LbjnMwCViF43pwErKmoFv7iGxQdCeQ.jpeg",
          href: "/books/zattar",
          accentColor: "#2E8B57",
        },
        {
          id: "amara",
          type: "book",
          tag: "AMARA: LA PRINCESA REBELDE",
          title: "AMARA",
          subtitle: "GUERRERA DEL KONGO",
          description: "Hija de un rey pero guerrera por justicia. Amara desafía la tradición para liderar a su pueblo hacia la victoria.",
          buttonText: "DESCUBRIR AMARA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1173-wrVJYiZhuW6ZvCM0Xronsu544ccrqV.jpeg",
          href: "/#hero",
          accentColor: "#1E90B3",
        },
        {
          id: "zaiko",
          type: "book",
          tag: "ZAIKO: REY DE LAS CALLES",
          title: "ZAIKO",
          subtitle: "LA LEYENDA DE ZAIKO",
          description: "Forjado en Kivu del Norte y Kinshasa. Zaiko construyó el imperio más temido con voluntad de hierro y fuerza africana.",
          buttonText: "DESCUBRIR ZAIKO",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1175-njlosetUOsqZszKylrOXsIRLw0l3s7.jpeg",
          href: "/books/zaiko",
          accentColor: "#2E8B57",
        }
      ]
    },
    zu: {
      slides: [
        {
          id: "isolele",
          type: "book",
          tag: "WAMUKELEKILE E-ISOLELE",
          title: "OKHETHIWEYO",
          subtitle: "UMHLABA WOKUQALA WAMAQHAWE AMNYAMA ASE-AFRIKA",
          description:
            "I-Isolele wumbono womhlaba owazalelwa ukuvuselela umphefumulo wokuxoxwa kwezindaba zase-Afrika, umbuso wezinganekwane lapho amaqhawe akhethwa khona isiphetho, imibuso engakhohlwa, namandla okhokho aphila kuwo wonke amakhasi, zonke iziprofetho, nazo zonke izimpi. Wonke umntwana ofunda i-Isolele uzothola amaqhawe abukeka njengaye, akhuluma ulimi lwakhe, avikela umhlaba wakhe, futhi ahlonipha okhokho bakhe. Lokhu kwenzelwa isizukulwane esizayo samakhosi, amakhosikazi, amaqhawe, abasunguli, nabaxoxi bezindaba. I-ISOLELE wumhlaba wokuqala wamaqhawe amnyama ase-Afrika osuselwa efubeni le-Kongo yangempela, owakhiwe e-DRC futhi wabelwa umhlaba wonke.",
          buttonText: "HLOLA UMHLABA",
          image:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Cover%20Book%202%20Isolele-QCEiRH2KJp3oFt4O31Qocqap3nLgiJ.jpg",
          href: "/books/isolele",
          accentColor: "#F6B800",
        },
        {
          id: "zaiire",
          type: "book",
          tag: "U-ZAIIRE: INKOSANA YASE-KONGO",
          title: "U-ZAIIRE",
          subtitle: "UMGINTI WESIPHETHO",
          description:
            "U-Zaiire akazalwanga eyiqhawe. Uzalwe ekhethiwe. Indodana kaShango, inkosi yezulu, neNkosazana uKimoya, indlovukazi eyiqhawe yozalo lwenkosi yase-Kongo. U-Zaiire uthwele imihlaba emibili ngaphakathi kuye. Umhlaba wabantu wamakhosi, izimpi, nokuzidela. Kanye nomhlaba waphezulu wamandla okhokho, isiphetho somhlaba, namandla amadala kunanoma yimuphi umbuso.",
          buttonText: "THOLA U-ZAIIRE",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG-20260308-WA0059-75yxyGjuDt9hhqXF6obymfG8BpNLz4.jpg",
          href: "/books/zaiire",
          accentColor: "#F6B800",
        },
        {
          id: "makanda",
          type: "book",
          tag: "UZALO LUKA-MAKANDA - INCWADI I",
          title: "U-MAKANDA",
          subtitle: "UZALO OLUCASHILE",
          description:
            "Ekujuleni kwe-Central Africa kwakunempucuko umhlaba owawungahloselwe ukuyazi. Ephapheme ngokomoya. Ethuthukile kwezobuchwepheshe. Evikelwe yi-Sacred Flame. Lapho amabutho angaphandle efika ezofuna okwabo, ama-Makanda awayinganga. Anyamalala. Idolobha labo alizange lilahleke. Lalilindele lowo ozalelwe ukuphatha ilangabi futhi. Uzalo luka-Makanda wuchungechunge lwamahlaya amnyama lase-Afrika oluzalwe empucukweni yase-Kongo, umbuso ofihliwe osukela enhliziyweni ye-DRC.",
          buttonText: "THOLA U-MAKANDA",
          image:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/KIMOYA%20-%20THE%20RISING%20KANDAKE-kpNHOGXUp1l9A5z7uJ2Z4kI3v7e0ek.jpg",
          href: "/books/makanda",
          accentColor: "#C0392B",
        },
        {
          id: "bambula",
          type: "book",
          tag: "U-BAMBULA: INGANE YESIGQI",
          title: "U-BAMBULA",
          subtitle: "ISIGUBHU ESINGCWELE",
          description:
            "Ngaphambi kwamazwi, kwakunesigqi. U-Bambula kwakuyingane eyayizwa konke. Lapho izigubhu zithathwa kanti nezwe lithula, wagcina isigqi siphila ngaphakathi kuye. Ehlomile ngesigubhu esingcwele, uhamba phakathi kwezwe lomoya nelabaphilayo. Akalwi ukuze acebe. Uvikela ukuze akhumbule. U-Bambula uyiqhawe elimnyama lase-Afrika elisuselwa emasikweni omoya wase-Kongo, lapho isigubhu esingcwele sixhumanisa abaphilayo nokhokho.",
          buttonText: "THOLA U-BAMBULA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Bambula%201-UAlmQoZVy1GslUfmVvqc5bdDDdEQdX.jpg",
          href: "/books/bambula",
          accentColor: "#B3541E",
        },
        {
          id: "mokele",
          type: "book",
          tag: "U-MOKELE: KUSUKELA ENGANENI KUYA ENKOSINI",
          title: "U-MOKELE",
          subtitle: "KUSUKELA EZITALADINI ZASE-KINSHASA",
          description:
            "U-Mokele akazalwanga eyinkosi. Uzalelwe ekuhluphekeni. Izitaladi zase-Kinshasa zimfundisile ngaphambi kokuba isikole sikwenze lokho, lapho ukwethembeka kubuthakathaka, udlame luyinto ejwayelekile, kanti nokusinda kuyikho konke. Kusukela enganeni kuya kumhushuluzi kuye enkosini. Akha amandla, imali, nenhlonipho. E-Kinshasa, kungenzeka udliwe… Noma ube yisilo esidlayo. U-Mokele ngumlingiswa wamahlaya amnyama lase-Afrika ozalelwe ezitaladini zase-Kinshasa, e-DRC, lapho ukusinda kwakha imibuso.",
          buttonText: "THOLA U-MOKELE",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Mokele.png-7sTyiUJYN8wJbiGll8YdVThtR4F8FT.jpeg",
          href: "/books/mokele",
          accentColor: "#4169E1",
        },
        {
          id: "kufu",
          type: "book",
          tag: "I-KUFU: UMDLALO WEZINKADI WASE-AFRIKA",
          title: "I-KUFU",
          subtitle: "IZINKADI EZINGU-103. UMQSHELE OWODWA.",
          description:
            "Lona akuyona nje umdlalo wezinkadi. Kuyisiko. Qoqa amabutho akho. Yakha umbuso wakho. Hlula wonke umuntu etafuleni. Kodwa ukuze uthole umqhele kunendlela eyodwa kuphela yokuwina. Kumele uphakamise izwi lakho ubize igama lenkosi phezulu. Ngemuva kwalokho othile ufaka umginti ekhanda lakho. Hhayi ngesandla sakho. Kodwa ngesomunye. Ngoba inkosi yangempela ayigcotshwa iyodwa. I-KUFU kulapho ubukhosi base-Afrika buba yinto oyizwayo ezandleni zakho, oyizwayo ezwini lakho, n oyithwele entanyeni yakho. Wonke umdlalo wukugcotshwa. Wonke owinile uyinkosi. I-Kufu wumdlalo wokuqala wezinkadi wase-Afrika ohlanganisa amakhosi, amakhosikazi, namaqhawe ase-Afrika avela empucukweni yase-Kongo. Izinkadi ezingu-103. Umqhele owodwa. Kwethulwa ngoJuni 30, 2026.",
          buttonText: "THOLA I-KUFU",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_20260321_113436-ktAJOL2e0SS0pkTY6aPnn7aBKxr3pq.jpg",
          href: "/books/kufu",
          accentColor: "#F8B90D",
        },
        {
          id:"zattar",
          type: "book",
          tag: "U-ZATTAR: INKOSANA YOKUGCINA",
          title: "U-ZATTAR",
          subtitle: "INKOSANA YOKUGCINA YASE-KONGO",
          description:
            "Lapho Isiphetho Simncisha Umbuso Owodwa, Wanquma Ukuyithatha Yonke. Inkosana u-Zattar wazalelwa ukuzuza isihlalo sobukhosi sase-Bapindi. Kodwa lapho okhokho bekhetha omunye, okuthile ngaphakathi kuye akuzange kuphuke. Kwavutha amalangabi. Wafunda ngezimpi zokuqala nezesibili zase-Vegas, izinganekwane zokucekelwa phansi ezazamazamisa umhlaba ngaphambi kokuba azalwe. Lapho abanye bebona isixwayiso, u-Zattar wabona imephu. Waqala iMpi Yesithathu yase-Vegas. Hhayi ngenxa yobuhlanya. Hhayi ngenxa yobuhlungu. Kodwa ngenxa yokuthi wabuka yonke indawo yendawo yonke futhi wafika esiphethweni esisodwa: Inomnikazi. Futhi lowo mnikazi ngu-Zattar. Akakhethwanga. Ngakho-ke wakhetha indawo yonke esikhundleni salokho. U-Zattar uyisitha esimnyama sase-Afrika esiyingozi kakhulu kumahlaya, iNkosana yase-Bapindi eyenqaba isiphetho futhi yamemezela impi kuyo yonke indawo yonke.",
          buttonText: "THOLA U-ZATTAR",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/e9c64c65-3717-4fe3-a391-885767df3303-LbjnMwCViF43pwErKmoFv7iGxQdCeQ.jpeg",
          href: "/books/zattar",
          accentColor: "#2E8B57",
        },
        {
          id: "amara",
          type: "book",
          tag: "U-AMARA: INKOSAZANA EYISIHLWANE",
          title: "U-AMARA",
          subtitle: "INKOSAZANA EYISIHLWANE YASE-KONGO",
          description:
            "U-Amara uyinkosazana eyisihlwane yase-Kongo. Indodakazi enolaka yenkosi enamandla, uphikisana namasiko futhi ulwela ubulungiswa ezweni elizama ukumthulisa. Lapho umbuso wakhe usongelwa amabutho angaphandle, u-Amara uthatha izikhali ukuze avikele abantu bakhe futhi abuyise indawo yakhe efanele esihlalweni sobukhosi. U-Amara ngumlingiswa wamahlaya amnyama lase-Afrika ozalwe ozalweni lwenkosi lwempucuko yase-Kongo, lapho amakhosazana engekona nje kuphela izibalo zobuhle, kodwa engamaqhawe amiselwe ukuhola abantu bawo ekunqobeni.",
          buttonText: "THOLA U-AMARA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1173-wrVJYiZhuW6ZvCM0Xronsu544ccrqV.jpeg",
          href: "/#hero",
          accentColor: "#1E90B3",
        },
        {
          id: "zaiko",
          type: "book",
          tag: "U-ZAIKO: INKOSI YOKUGCINA YEZITALADI ZASE-KIVU",
          title: "U-ZAIKO",
          subtitle: "UMLANDO KA-ZAIKO",
          description:
            "Wazalwa e-North Kivu. Wakhiwa e-Kinshasa. U-Zaiko kwakungamele aphile. Kodwa ukusinda kwakungenele. Ezweni elibuswa amandla, imali, nokwesaba, usukela ezeni. Hhayi njengeqhawe. Kodwa njengamandla. Kanye nomfowabo, wakha umbuso owesatshwa kakhulu i-Kivu eyake yawazi. Awukho umqhele owanikezwa. Awukho isiphetho esabhalwa. Konke kwathathwa. Wonke umbuso wakhiwa phezu komlotha walabo abafika ngaphambili. Lona umlando wokuthi umuntu oyedwa waliphikisa kanjani isiphetho ngokwakhe futhi waqopha igama lakhe emlandweni wase-Afrika ngensimbi nangentando. U-Zaiko uyiqhawe lamahlaya amnyama lase-Afrika elizalwe e-North Kivu, e-DRC, lapho impi yakha khona inkosi eyesatshwa kakhulu izitaladi ezake yazazi.",
          buttonText: "THOLA U-ZAIKO",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1175-njlosetUOsqZszKylrOXsIRLw0l3s7.jpeg",
          href: "/books/zaiko",
          accentColor: "#2E8B57",
        }
      ]
    },

    xh: {
      slides: [
        {
          id: "isolele",
          type: "book",
          tag: "WAMKELEKILE E-ISOLELE",
          title: "ONYULIWEYO",
          subtitle: "INDALO YOKUQALA YAMAQHAWE AMNYAMA ASE-AFRIKA",
          description:
            "I-Isolele yindalo yombono eyazalelwa ukubuyisela umphefumulo wokubaliswa kwamabali ase-Afrika, ubukhosi basentsomini apho amaqhawe anyulwa sisiphetho. Imibuso engalibalekiyo namandla ezinyanya aphila kuwo onke amaphepha neziprofeto. Wonke umntwana ofunda i-Isolele uya kufumana amaqhawe afana naye, athetha ulwimi lwakhe, kwaye ahlonipha izinyanya zakhe. Le nto yenzelwe isizukulwane esizayo seekumkani, amagorha, nabaqambi bebali. I-ISOLELE yindalo yokuqala yamaqhawe amnyama ase-Afrika esekelwe kwilifa lokwenyani lase-Kongo, eyenziwe e-DRC yenzelwa umhlaba wonke.",
          buttonText: "PHANDA INDALO",
          image:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Cover%20Book%202%20Isolele-QCEiRH2KJp3oFt4O31Qocqap3nLgiJ.jpg",
          href: "/books/isolele",
          accentColor: "#F6B800",
        },
        {
          id: "zaiire",
          type: "book",
          tag: "U-ZAIIRE: INKOSANA YASE-KONGO",
          title: "U-ZAIIRE",
          subtitle: "INTLOKOMO YESIPHETHO",
          description:
            "U-Zaiire akazalwanga eliqhawe. Uzelwe enyuliwe. Unyana kaShango, inkosi yeendudumo, nenkosazana uKimoya, ukumkanikazi eliqhawe lozalo lwase-Kongo. U-Zaiire uphethe imihlaba emibini ngaphakathi kuye. Umhlaba wabantu weekumkani neemfazwe, nomhlaba wezinyanya onamandla amadala kunayo yonke imibuso.",
          buttonText: "FUMANA U-ZAIIRE",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG-20260308-WA0059-75yxyGjuDt9hhqXF6obymfG8BpNLz4.jpg",
          href: "/books/zaiire",
          accentColor: "#F6B800",
        },
        {
          id: "makanda",
          type: "book",
          tag: "UZALO LUKA-MAKANDA - INCWADI I",
          title: "U-MAKANDA",
          subtitle: "UZALO OLUFIHLIWEYO",
          description:
            "Ekujuleni kwe-Central Africa kwakukho impucuko umhlaba owawungamelanga kuyazi. Ephakamileyo ngokomoya kwaye ephambili ngezobuchwepheshe. Evikelwe yi-Sacred Flame. Xa amabutho angaphandle efika, ama-Makanda anyamalala ukukhusela imfihlo yawo. Uzalo luka-Makanda lusekelwe kwi-DRC, ubutyebi obufihliweyo bentliziyo ye-Afrika.",
          buttonText: "FUMANA U-MAKANDA",
          image:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/KIMOYA%20-%20THE%20RISING%20KANDAKE-kpNHOGXUp1l9A5z7uJ2Z4kI3v7e0ek.jpg",
          href: "/books/makanda",
          accentColor: "#C0392B",
        },
        {
          id: "bambula",
          type: "book",
          tag: "U-BAMBULA: UMNTWANA WESINGQI",
          title: "U-BAMBULA",
          subtitle: "IGUBU ELINGCWELE",
          description:
            "Exhobile ngegubu elingcwele, uBambula uhamba phakathi kwelizwe lemimoya nelabaphilayo. Akalwi ukuze atshabalalise, ukhusela ukuze isingqi somhlaba singaze sicime. Isithethe somoya wase-Kongo apho igubu lidibanisa abaphilayo nezinyanya.",
          buttonText: "FUMANA U-BAMBULA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Bambula%201-UAlmQoZVy1GslUfmVvqc5bdDDdEQdX.jpg",
          href: "/books/bambula",
          accentColor: "#B3541E",
        },
        {
          id: "mokele",
          type: "book",
          tag: "U-MOKELE: UKUSUKA EZITALATWENI",
          title: "U-MOKELE",
          subtitle: "IZITALATO ZASE-KINSHASA",
          description:
            "U-Mokele akazalwanga eyikumkani. Izitalato zase-Kinshasa zimfundise ukuba ukusinda yinto yonke. Wakha umbuso wakhe ngamandla nentlonipho kule jungle yasedolophini. E-Kinshasa, unokuba lixhoba... okanye ube likatshulange.",
          buttonText: "FUMANA U-MOKELE",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Mokele.png-7sTyiUJYN8wJbiGll8YdVThtR4F8FT.jpeg",
          href: "/books/mokele",
          accentColor: "#4169E1",
        },
        {
          id: "kufu",
          type: "book",
          tag: "I-KUFU: UMDLALO WAMAKHADI",
          title: "I-KUFU",
          subtitle: "AMAKHADI AYI-103. ISITHSABA ESINYE.",
          description:
            "Lo akulo mdlalo nje, sisithethe. Hlanganisa amagorha akho kwaye wakhe ubukhosi bakho. Ukuze uphumelele, kufuneka ubize igama lekumkani phezulu. Umdlalo wase-Afrika ophefumlelwe yimpucuko yase-Kongo. Uphehlelelo: 30 Juni 2026.",
          buttonText: "FUMANA I-KUFU",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_20260321_113436-ktAJOL2e0SS0pkTY6aPnn7aBKxr3pq.jpg",
          href: "/books/kufu",
          accentColor: "#F8B90D",
        },
        {
          id: "zattar",
          type: "book",
          tag: "U-ZATTAR: INKOSANA EWILEYO",
          title: "U-ZATTAR",
          subtitle: "INKOSANA YOKUGQIBELA YASE-KONGO",
          description:
            "Xa isiphetho simvimbe itrone, wagqiba kwelokuba ayithathe yonke indalo. U-Zattar lolona tshaba luyingozi kakhulu kwi-Isolele, inkosana evakalise imfazwe kwinyani uqobo lwayo.",
          buttonText: "FUMANA U-ZATTAR",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/e9c64c65-3717-4fe3-a391-885767df3303-LbjnMwCViF43pwErKmoFv7iGxQdCeQ.jpeg",
          href: "/books/zattar",
          accentColor: "#2E8B57",
        },
        {
          id: "amara",
          type: "book",
          tag: "U-AMARA: INKOSAZANA ELIQHAWE",
          title: "U-AMARA",
          subtitle: "INKOSAZANA ENGONCEDIYO",
          description:
            "Intombi yekumkani kodwa eliqhawe ngokhetho, uAmara ucela umngeni kwizithethe ukukhusela abantu bakhe. Kwimpucuko yase-Kongo, iinkosazana ngamagorha amiselwe ukoyisa.",
          buttonText: "FUMANA U-AMARA",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1173-wrVJYiZhuW6ZvCM0Xronsu544ccrqV.jpeg",
          href: "/#hero",
          accentColor: "#1E90B3",
        },
        {
          id: "zaiko",
          type: "book",
          tag: "U-ZAIKO: INKOSI YEZITALATO ZASE-KIVU",
          title: "U-ZAIKO",
          subtitle: "IBALI LIKAZAIKO",
          description:
            "Wazalelwa e-North Kivu, wakhulela e-Kinshasa. U-Zaiko wakha ubukhosi oboyikekayo ngentsimbi nangentando yakhe. Ibali lase-Afrika lamandla nobugorha emva kokusinda ekufeni.",
          buttonText: "FUMANA U-ZAIKO",
          image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1175-njlosetUOsqZszKylrOXsIRLw0l3s7.jpeg",
          href: "/books/zaiko",
          accentColor: "#2E8B57",
        }
      ]
    } 
};
