export const characterData = {
  zaiire: {
    id: "zaiire",
    nameKey: "character_zaiire_name",
    titleKey: "character_zaiire_title",
    shortDescKey: "character_zaiire_short_desc",
    longDescKey: "character_zaiire_long_desc",
    bookNameKey: "product_zaiire_name",
    bookDescKey: "product_zaiire_desc",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ZAIIRE%20-%20PRINCE%20OF%20KONGO-hmOq1ET63L87xXbWVilEom8IqvT0jo.jpg",
    color: "#9B7E38",
    status: "PRE-ORDER",
  },
  kimoya: {
    id: "kimoya",
    nameKey: "character_kimoya_name",
    titleKey: "character_kimoya_title",
    shortDescKey: "character_kimoya_short_desc",
    longDescKey: "character_kimoya_long_desc",
    bookNameKey: "product_kimoya_name",
    bookDescKey: "product_kimoya_desc",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/KIMOYA%20-%20THE%20RISING%20KANDAKE-kpNHOGXUp1l9A5z7uJ2Z4kI3v7e0ek.jpg",
    color: "#E8A77A",
    status: "LIMITED",
  },
  bambula: {
    id: "bambula",
    nameKey: "character_bambula_name",
    titleKey: "character_bambula_title",
    shortDescKey: "character_bambula_short_desc",
    longDescKey: "character_bambula_long_desc",
    bookNameKey: "product_bambula_name",
    bookDescKey: "product_bambula_desc",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/BAMBULA-placeholder.jpg",
    color: "#8B4513",
    status: "COMING SOON",
  },
  mokele: {
    id: "mokele",
    nameKey: "character_mokele_name",
    titleKey: "character_mokele_title",
    shortDescKey: "character_mokele_short_desc",
    longDescKey: "character_mokele_long_desc",
    bookNameKey: "product_mokele_name",
    bookDescKey: "product_mokele_desc",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/MOKELE-placeholder.jpg",
    color: "#2E7D32",
    status: "COMING SOON",
  },
  assemblee: {
    id: "assemblee-isolele",
    nameKey: "character_assemblee_name",
    titleKey: "character_assemblee_title",
    shortDescKey: "character_assemblee_short_desc",
    longDescKey: "character_assemblee_long_desc",
    bookNameKey: "product_assemblee_name",
    bookDescKey: "product_assemblee_desc",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ASSEMBLEE-placeholder.jpg",
    color: "#4A148C",
    status: "COMING SOON",
  },
  kufulula: {
    id: "king-kufulula",
    nameKey: "character_kufulula_name",
    titleKey: "character_kufulula_title",
    shortDescKey: "character_kufulula_short_desc",
    longDescKey: "character_kufulula_long_desc",
    bookNameKey: "product_kufulula_name",
    bookDescKey: "product_kufulula_desc",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/KING-KUFULULA-placeholder.jpg",
    color: "#B8860B",
    status: "AVAILABLE",
  },
}

export type CharacterKey = keyof typeof characterData
