import type { Dispatch, ReactNode, SetStateAction } from "react";
import type { ArticleStatus, TranslationStatus } from "@/generated/prisma/client";
import type { ArticleBlock, ArticleBlockType } from "../../model/article-blocks";
import type { TranslationLocaleSummary } from "../../model/article-translation-workflow";
import type { SupportedLocale } from "@/shared/i18n/locales";

export type ArticleEditorPreviewMode = "edit" | "split" | "preview";
export type ArticleEditorSidebarPanel = "structure" | "seo" | "media";

export type ArticleEditorProps = {
    id: string;
    translationGroupId: string;
    locale: string;
    articleLocale: string;
    initialTitle: string;
    initialExcerpt: string;
    initialCoverImage: string | null;
    initialSeoTitle: string | null;
    initialSeoDescription: string | null;
    initialBlocks: ArticleBlock[];
    initialStatus: ArticleStatus;
    initialTranslationStatus: TranslationStatus;
    initialSourceVersion: number;
    initialTranslatedFromVersion: number | null;
    initialTranslations: TranslationLocaleSummary[];
    initialWarnings: string[];
};

export type ArticleEditorContextValue = {
    id: string;
    translationGroupId: string;
    locale: string;
    articleLocale: string;
    translationStatus: TranslationStatus;
    sourceVersion: number;
    translatedFromVersion: number | null;
    translations: TranslationLocaleSummary[];
    title: string;
    setTitle: (value: string) => void;
    excerpt: string;
    setExcerpt: (value: string) => void;
    coverImage: string;
    setCoverImage: (value: string) => void;
    seoTitle: string;
    setSeoTitle: (value: string) => void;
    seoDescription: string;
    setSeoDescription: (value: string) => void;
    status: ArticleStatus;
    blocks: ArticleBlock[];
    setBlocks: Dispatch<SetStateAction<ArticleBlock[]>>;
    warnings: string[];
    previewMode: ArticleEditorPreviewMode;
    setPreviewMode: (value: ArticleEditorPreviewMode) => void;
    activeSidebarPanel: ArticleEditorSidebarPanel;
    setActiveSidebarPanel: (value: ArticleEditorSidebarPanel) => void;
    focusedBlockId: string | null;
    setFocusedBlockId: (id: string | null) => void;
    isSaving: boolean;
    isStatusPending: boolean;
    isDeleting: boolean;
    isUploading: boolean;
    isSwitchingLocale: boolean;
    uploadError: string | null;
    activityMessage: string | null;
    coverImageInputId: string;
    saveArticle: () => void;
    changeStatus: (value: ArticleStatus) => void;
    deleteArticle: () => void;
    switchLocale: (locale: SupportedLocale) => Promise<void>;
    triggerCoverImagePicker: () => void;
    addBlock: (type: ArticleBlockType, index?: number) => void;
    duplicateBlock: (id: string) => void;
    removeBlock: (id: string) => void;
    moveBlock: (id: string, delta: number) => void;
    updateBlock: (block: ArticleBlock) => void;
    focusBlock: (id: string) => void;
    uploadImageFile: (file: File, blockId?: string) => Promise<void>;
};

export type ArticleEditorProviderProps = {
    value: ArticleEditorContextValue;
    children: ReactNode;
};
