import type { Character, CharacterSectionTranslations } from "./types";

export const CHARACTERS: Character[] = [
  {
    id: "zaire",
    name: "ZAIIRE",
    title: {
      en: "The Prince of Kongo and the Necklace of Destiny",
      fr: "Le Prince du Kongo et le Collier de la DestinÃ©e",
      pt: "O PrÃ­ncipe do Kongo e o Colar do Destino",
      es: "El PrÃ­ncipe del Kongo y el Collar del Destino",
      zu: "INkosana weKongo neneKhanga leNkomo",
      xh: "Inkosana yeKongo neKhanga leNkomo",
      sw: "Mkuu wa Kongo na Mkufu wa Hatimaye",
      ln: "Mwana wa Kongo mpe Mbele ya Suka",
    },
    description: "Son of thunder and royalty, chosen by the Necklace of Destiny.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ZAIIRE%20-%20PRINCE%20OF%20KONGO-hmOq1ET63L87xXbWVilEom8IqvT0jo.jpg",
    color: "#F6B800",
  },
  {
    id: "bambula",
    name: "BAMBULA",
    title: {
      en: "Child of Rhythm",
      fr: "Enfant du Rythme",
      pt: "Filha do Ritmo",
      es: "Hija del Ritmo",
      zu: "Umntwana weRhythm",
      xh: "Umntwana weRhythm",
      sw: "Mtoto wa Ritmu",
      ln: "Mwana wa Ndakisa",
    },
    description: "Warrior of the savannas, master of sacred fire and wild nature.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Bambula%201-UAlmQoZVy1GslUfmVvqc5bdDDdEQdX.jpg",
    color: "#B3541E",
  },
  {
    id: "kimoya",
    name: "MAKANDA",
    title: {
      en: "THE MOST POWERFUL Empire in History",
      fr: "L'EMPIRE LE PLUS PUISSANT de l'Histoire",
      pt: "O IMPÃ‰RIO MAIS PODEROSO da HistÃ³ria",
      es: "EL IMPERIO MÃS PODEROSO de la Historia",
      zu: "UMBUSO ONAMANDLA KAKHULU Emlandweni",
      xh: "UMBUSO ONAMANDLA KAKHULU Emlandweni",
      sw: "NCHI YENYE NGUVU ZAIDI ya Historia",
      ln: "BOKONZI OYO OYA NGUVU KAKHULU ya Biso",
    },
    description: "Warrior empress whose royal court holds the destiny of the continent in her hands.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG-20260323-WA0012-2zfYaTNiUmh8XgNPMwbkLcKExGX65Q.jpg",
    color: "#C0392B",
  },
  {
    id: "mokele",
    name: "MOKELE",
    title: {
      en: "Crowned by the Streets",
      fr: "CouronnÃ© par les Rues",
      pt: "Coroado pelas Ruas",
      es: "Coronado por las Calles",
      zu: "Ukhethiwe NgeSitolo",
      xh: "Ukhethiwe NgeSitolo",
      sw: "Akamata Taji kutoka Mitaani",
      ln: "Komonzi na Malela",
    },
    description: "Heir of urban chaos and ancestral power â€” Crowned by the Streets.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/5bdc2ecc-913b-412b-a840-2a5197cd801a.jpeg",
    color: "#4169E1",
  },
  {
    id: "kufulula",
    name: "HRM KING KUFULULA",
    title: {
      en: "Visionaryâ€¢ Cultural Architect â€¢ African Royalty",
      fr: "Visionnaireâ€¢ Architecte Culturel â€¢ RoyautÃ© Africaine",
      pt: "VisionÃ¡rioâ€¢ Arquiteto Cultural â€¢ Realeza Africana",
      es: "Visionarioâ€¢ Arquitecto Cultural â€¢ Realeza Africana",
      zu: "Ongaboniseleâ€¢ Umkhi weNtu â€¢ Umbuso weAfrika",
      xh: "Ongaboniseleâ€¢ Umkhi weNtu â€¢ Umbuso weAfrika",
      sw: "Mwenye Mawazoâ€¢ Mwalimu wa Kitamaduni â€¢ Ukurusi wa Afrika",
      ln: "Mwenye Longiâ€¢ Mokambi wa Boyokoliâ€¢ Mokonzi wa Bafriki",
    },
    description: "Legendary monarch, protector of the ISOLELE royal lineage.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/King%20kufulula-1pEeYE9t1QYruZhNooZuPw7Nkd1A8l.jpg",
    color: "#8B6914",
  },
  {
    id: "ensemble",
    name: "THE ISOLELE ASSEMBLY",
    title: {
      en: "The Chosen Ones United",
      fr: "Les Ã‰lus Unis",
      pt: "Os Escolhidos Unidos",
      es: "Los Elegidos Unidos",
      zu: "Abasakhethiwe Ahlangene",
      xh: "Abasakhethiwe Ahlangene",
      sw: "Wachaguzi Waameunganisha",
      ln: "Baya Likonde Bayambilakela",
    },
    description: "All warriors and queens of the ZAIIRE kingdom united in their splendor.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/c389067b-e5b3-4664-8c15-26b59810c68b.jpeg",
    color: "#9932CC",
  },
];

export const CHARACTER_SECTION_TRANSLATIONS: CharacterSectionTranslations = {
  title: {
    en: "THE CHOSEN ONES",
    fr: "LES Ã‰LUS",
    pt: "OS ESCOLHIDOS",
    es: "LOS ELEGIDOS",
    zu: "ABASAKHETHIWE",
    xh: "ABASAKHETHIWE",
    sw: "WACHAGUZI",
    ln: "BAYA LIKONDE",
  },
  subtitle: {
    en: "Meet the heroes, legends and guardians of the ISOLELE Universe.",
    fr: "Rencontrez les hÃ©ros, lÃ©gendes et gardiens de l'univers ISOLELE.",
    pt: "ConheÃ§a os herÃ³is, lendas e guardiÃµes do Universo ISOLELE.",
    es: "Conoce a los hÃ©roes, leyendas y guardianes del Universo ISOLELE.",
    zu: "Hlangana nengalo, inganekwane nezikhulu sezwe se-ISOLELE.",
    xh: "Hlangana nengalo, inganekwane nezikhulu sezwe se-ISOLELE.",
    sw: "Kamatia wabunga, hadithi na walinzi wa Ulimwengu wa ISOLELE.",
    ln: "Longa baninga, bambo mpe basolani ya Bambwe ya ISOLELE.",
  },
  discover: {
    en: "DISCOVER",
    fr: "DÃ‰COUVRIR",
    pt: "DESCOBRIR",
    es: "DESCUBRIR",
    zu: "THOLA",
    xh: "THOLA",
    sw: "GUNDUA",
    ln: "TALA",
  },
};

