
export const newsData = {
  en: {
  title: "Latest News",
  minutesReadLabel: "min read",
  readArticleLabel: "READ ARTICLE",
  viewAllLabel: "VIEW ALL NEWS",
  articles: [
    {
      id: 1,
      category: "HISTORY",
      categoryColor: "#D4AF37",
      title: "How Makanda reclaims a lost African empire in modern comics",
      excerpt: "A closer look at the royal mythology, symbols, and historical echoes shaping one of ISOLELE's boldest worlds.",
      readTime: "5",
      date: "March 2026",
      image: "/events/wakanda-makanda-royal.webp",
    },
    {
      id: 2,
      category: "CULTURE",
      categoryColor: "#B3541E",
      title: "Why ISOLELE is becoming a memory project as much as a comic universe",
      excerpt: "From diaspora identity to cultural restoration, the project is resonating far beyond entertainment.",
      readTime: "8",
      date: "February 2026",
      image: "/events/african-empire-luxury.webp",
    },
    {
      id: 3,
      category: "RESEARCH",
      categoryColor: "#4169E1",
      title: "Inside the references behind the Makanda manuscript",
      excerpt: "The design language of courts, sacred fire, and royal archives that shaped this new mythology.",
      readTime: "6",
      date: "January 2026",
      image: "/events/courtroom-makanda.webp",
    },
  ],
},
  fr: {
    title: "Dernières Actualités",
    minutesReadLabel: "min de lecture",
    readArticleLabel: "LIRE L'ARTICLE",
    viewAllLabel: "VOIR TOUTES LES ACTUALITÉS",
    articles: [
      {
        id: 1,
        category: "HISTOIRE",
        categoryColor: "#D4AF37",
        title: "Comment Makanda reconquiert un empire africain perdu dans les bandes dessinées modernes",
        excerpt: "Un regard approfondi sur la mythologie royale, les symboles et les échos historiques qui façonnent l'un des mondes les plus audacieux d'ISOLELE.",
        readTime: "5",
        date: "Mars 2026",
        image: "/events/wakanda-makanda-royal.webp",
      },
      {
        id: 2,
        category: "CULTURE",
        categoryColor: "#B3541E",
        title: "Pourquoi ISOLELE devient un projet de mémoire autant qu'un univers de bandes dessinées",
        excerpt: "De l'identité diasporique à la restauration culturelle, le projet résonne bien au-delà du divertissement.",
        readTime: "8",
        date: "Février 2026",
        image: "/events/african-empire-luxury.webp",
      },
      {
        id: 3,
        category: "RECHERCHE",
        categoryColor: "#4169E1",
        title: "À l'intérieur des références derrière le manuscrit Makanda",
        excerpt: "Le langage visuel des cours, du feu sacré et des archives royales qui ont façonné cette nouvelle mythologie.",
        readTime: "6",
        date: "Janvier 2026",
        image: "/events/courtroom-makanda.webp",
      },
    ],
  },
  pt: {
    title: "Últimas Notícias",
    minutesReadLabel: "min de leitura",
    readArticleLabel: "LER ARTIGO",
    viewAllLabel: "VER TODAS AS NOTÍCIAS",
    articles: [
      {
        id: 1,
        category: "HISTÓRIA",
        categoryColor: "#D4AF37",
        title: "Como Makanda recupera um império africano perdido nos comics modernos",
        excerpt: "Um olhar mais atento à mitologia real, aos símbolos e aos ecos históricos que moldam um dos mundos mais ousados da ISOLELE.",
        readTime: "5",
        date: "Março 2026",
        image: "/events/wakanda-makanda-royal.webp",
      },
      {
        id: 2,
        category: "CULTURA",
        categoryColor: "#B3541E",
        title: "Por que a ISOLELE está a tornar-se tanto um projeto de memória como um universo de comics",
        excerpt: "Da identidade da diáspora à restauração cultural, o projeto ressoa muito além do entretenimento.",
        readTime: "8",
        date: "Fevereiro 2026",
        image: "/events/african-empire-luxury.webp",
      },
      {
        id: 3,
        category: "INVESTIGAÇÃO",
        categoryColor: "#4169E1",
        title: "Dentro das referências por trás do manuscrito Makanda",
        excerpt: "A linguagem visual das cortes, do fogo sagrado e dos arquivos reais que moldaram esta nova mitologia.",
        readTime: "6",
        date: "Janeiro 2026",
        image: "/events/courtroom-makanda.webp",
      },
    ],
  },
  es: {
    title: "Últimas Noticias",
    minutesReadLabel: "min de lectura",
    readArticleLabel: "LEER ARTÍCULO",
    viewAllLabel: "VER TODAS LAS NOTICIAS",
    articles: [
      {
        id: 1,
        category: "HISTORIA",
        categoryColor: "#D4AF37",
        title: "Cómo Makanda recupera un imperio africano perdido en los cómics modernos",
        excerpt: "Una mirada más cercana a la mitología real, los símbolos y los ecos históricos que dan forma a uno de los mundos más audaces de ISOLELE.",
        readTime: "5",
        date: "Marzo 2026",
        image: "/events/wakanda-makanda-royal.webp",
      },
      {
        id: 2,
        category: "CULTURA",
        categoryColor: "#B3541E",
        title: "Por qué ISOLELE se está convirtiendo tanto en un proyecto de memoria como en un universo de cómics",
        excerpt: "De la identidad de la diáspora a la restauración cultural, el proyecto resuena mucho más allá del entretenimiento.",
        readTime: "8",
        date: "Febrero 2026",
        image: "/events/african-empire-luxury.webp",
      },
      {
        id: 3,
        category: "INVESTIGACIÓN",
        categoryColor: "#4169E1",
        title: "Dentro de las referencias detrás del manuscrito Makanda",
        excerpt: "El lenguaje visual de las cortes, el fuego sagrado y los archivos reales que dieron forma a esta nueva mitología.",
        readTime: "6",
        date: "Enero 2026",
        image: "/events/courtroom-makanda.webp",
      },
    ],
  },
  zu: {
    title: "Izindaba Ezisha",
    minutesReadLabel: "imizuzu yokufunda",
    readArticleLabel: "FUNDA ISIHLOKO",
    viewAllLabel: "BONA ZONKE IZINDABA",
    articles: [
      {
        id: 1,
        category: "UMLANDO",
        categoryColor: "#D4AF37",
        title: "Indlela iMakanda ebuyisela ngayo umbuso wase-Afrika olahlekile emacomics anamuhla",
        excerpt: "Ukubuka eduze inganekwane yasebukhosini, izimpawu, kanye nemiphumela yomlando eyakha elinye lemihlaba enesibindi ye-ISOLELE.",
        readTime: "5",
        date: "Mashi 2026",
        image: "/events/wakanda-makanda-royal.webp",
      },
      {
        id: 2,
        category: "AMASIKO",
        categoryColor: "#B3541E",
        title: "Kungani i-ISOLELE isiba iphrojekthi yenkumbulo kanye nomhlaba wamacomics",
        excerpt: "Kusukela ebunikazini bokuhlakazeka kuya ekubuyiselweni kwamasiko, iphrojekthi ithinta ngale kokuzijabulisa.",
        readTime: "8",
        date: "Febhuwari 2026",
        image: "/events/african-empire-luxury.webp",
      },
      {
        id: 3,
        category: "UCWANINGO",
        categoryColor: "#4169E1",
        title: "Ngaphakathi kwezinsalela ezingemuva kombhalo waseMakanda",
        excerpt: "Ulimi lokwakheka lwezinkantolo, umlilo ongcwele, kanye nemibhalo yasebukhosini eyakha le nganekwane entsha.",
        readTime: "6",
        date: "Januwari 2026",
        image: "/events/courtroom-makanda.webp",
      },
    ],
  },
  xh: {
    title: "Iindaba Ezitsha",
    minutesReadLabel: "imizuzu yokufunda",
    readArticleLabel: "FUNDA INQAKU",
    viewAllLabel: "BONA ZONKE IINDABA",
    articles: [
      {
        id: 1,
        category: "IMBALI",
        categoryColor: "#D4AF37",
        title: "Indlela iMakanda ebuyisela ngayo ubukumkani base-Afrika obulahlekileyo kwii-comics zanamhlanje",
        excerpt: "Ukujonga nzulu intsomi yasebukhosini, iimpawu, kunye nemiphumela yembali ebumba elinye lamahlabathi anesibindi e-ISOLELE.",
        readTime: "5",
        date: "Matshi 2026",
        image: "/events/wakanda-makanda-royal.webp",
      },
      {
        id: 2,
        category: "INKCUBEKO",
        categoryColor: "#B3541E",
        title: "Kutheni i-ISOLELE isiba yiprojekthi yenkumbulo kunye nehlabathi lee-comics",
        excerpt: "Ukususela kubunikazi bokuchithakala ukuya ekubuyiseleni kwenkcubeko, iprojekthi ifikelela ngaphaya kokuzonwabisa.",
        readTime: "8",
        date: "Febhuwari 2026",
        image: "/events/african-empire-luxury.webp",
      },
      {
        id: 3,
        category: "UPHANDO",
        categoryColor: "#4169E1",
        title: "Ngaphakathi kwezalathiso ezisemva kombhalo waseMakanda",
        excerpt: "Ulwimi lokuyila lweenkundla, umlilo ongcwele, kunye nemibhalo yasebukhosini eyabumba le ntsomi intsha.",
        readTime: "6",
        date: "Janyuwari 2026",
        image: "/events/courtroom-makanda.webp",
      },
    ],
  },
  sw: {
    title: "Habari za Hivi Karibuni",
    minutesReadLabel: "dakika za kusoma",
    readArticleLabel: "SOMA MAKALA",
    viewAllLabel: "ONA HABARI ZOTE",
    articles: [
      {
        id: 1,
        category: "HISTORIA",
        categoryColor: "#D4AF37",
        title: "Jinsi Makanda inavyorejesha dola la Kiafrika lililopotea katika katuni za kisasa",
        excerpt: "Uchunguzi wa karibu wa hekaya za kifalme, alama, na mwangwi wa kihistoria unaounda mojawapo ya walimwengu jasiri zaidi wa ISOLELE.",
        readTime: "5",
        date: "Machi 2026",
        image: "/events/wakanda-makanda-royal.webp",
      },
      {
        id: 2,
        category: "UTAMADUNI",
        categoryColor: "#B3541E",
        title: "Kwa nini ISOLELE inakuwa mradi wa kumbukumbu kama vile ulimwengu wa katuni",
        excerpt: "Kutoka utambulisho wa diaspora hadi urejeshaji wa kiutamaduni, mradi huu unagusa mbali zaidi ya burudani.",
        readTime: "8",
        date: "Februari 2026",
        image: "/events/african-empire-luxury.webp",
      },
      {
        id: 3,
        category: "UTAFITI",
        categoryColor: "#4169E1",
        title: "Ndani ya marejeleo nyuma ya hati ya Makanda",
        excerpt: "Lugha ya kubuni ya mahakama, moto mtakatifu, na kumbukumbu za kifalme zilizounda hekaya hii mpya.",
        readTime: "6",
        date: "Januari 2026",
        image: "/events/courtroom-makanda.webp",
      },
    ],
  },
  ln: {
    title: "Nsango ya Sika",
    minutesReadLabel: "miniti ya kotanga",
    readArticleLabel: "TANGA LISOLO",
    viewAllLabel: "TALÁ NSANGO NYONSO",
    articles: [
      {
        id: 1,
        category: "LISOLO YA BOKONZI",
        categoryColor: "#D4AF37",
        title: "Ndenge Makanda azongisaka bokonzi ya Afrika oyo ebungaki na ba comics ya sika",
        excerpt: "Botali ya pembeni ya masapo ya bokonzi, bilembo, mpe makelele ya lisolo oyo esali moko ya mikili ya mpiko ya ISOLELE.",
        readTime: "5",
        date: "Sanza ya misato 2026",
        image: "/events/wakanda-makanda-royal.webp",
      },
      {
        id: 2,
        category: "MIMESENO",
        categoryColor: "#B3541E",
        title: "Mpo na nini ISOLELE ezali kokoma mosala ya bosikoli mpe mokili ya ba comics",
        excerpt: "Kobanda na bomoto ya diaspora kino na kozongisa mimeseno, mosala oyo ezali koyokana koleka kaka kosepela.",
        readTime: "8",
        date: "Sanza ya mibale 2026",
        image: "/events/african-empire-luxury.webp",
      },
      {
        id: 3,
        category: "BOLUKI",
        categoryColor: "#4169E1",
        title: "Na kati ya ba références oyo ezali sima ya mokanda ya Makanda",
        excerpt: "Monoko ya bokeli ya ba tribunal, moto ya bule, mpe ba archives ya bokonzi oyo esalaki masapo oyo ya sika.",
        readTime: "6",
        date: "Sanza ya yambo 2026",
        image: "/events/courtroom-makanda.webp",
      },
    ],
  },
};
